### ISSUE TITLE
nextcloud-snap bottleneck to handle more requests 

### ISSUE THREAD

**Issue by nirajvara** [nextcloud-snap/nextcloud-snap#1025]
Hi,

I have the latest nextcloud snap installed on ubuntu server.  Due to php-fpm default lower configuration, it's not able to handle the more concurrent client requests. 

I want to change the default setting to like that so It can handle more concurrent client requests 

pm = dynamic
pm.max_children = 120
pm.start_servers = 12
pm.min_spare_servers = 6
pm.max_spare_servers = 18

so Please guide how can I change the same to speed up client uploading.

**Comment by FuriouslyCurious** [comment]
Can these options be changed through SNAP SET command?  If not it might be a good idea to expose these as they seem vital for larger NextCloud installations.

**Comment by kyrofa** [comment]
> Can these options be changed through SNAP SET command?

Not currently, no. And the config is read-only, as well, so there's no way to do this today. However, I'm curious what makes you say the PHP FPM config is a lower configuration-- it's actually based on the detected amount of RAM so the snap scales with the hardware a bit better. My server ends up with over 300 max_children. It uses `ondemand` instead of `dynamic`, though, so that's really the only parameter that matters. If you think you've got a better-performing config that similarly scales with hardware, I'm all ears and am willing to change it for everyone, but you'll need to back up your claims.

**Comment by nirajvara** [comment]
We have 256 GB RAM and 32 Cpu's in server. As you mention your server ends up with many max_childern but here at my end this not happening.  when I have uploaded  3k files., the client sends all the files within few seconds only  but nextcloud handled only 4-6 files/second entry in the server.

what could be the reason my server not able to spawn more max_children and max_servers ! though my  server have the good RAM and Cpu's !

**Comment by kyrofa** [comment]
@nirajvara let me do some experimenting and get back to you.

**Comment by nirajvara** [comment]
@kyrofa  Waiting for your reply.  As you stated it uses default setting **ondemand**  but somehow it doesn't work. Please guide us to solve the same.

**Comment by nirajvara** [comment]
@kyrofa Please do the needful.

**Comment by Red-Eyed** [comment]
I'm also interested in this issue. 
I'm running NC on Raspberry Pi 4, and it sometimes hangs on iowait with a lot of processes `php-fpm` want try to set 
```
pm = static
pm.max_children = 8
```

**Comment by theoneandonly-vector** [comment]
any progress on this one?

**Comment by theoneandonly-vector** [comment]
keep it open

**Comment by Mte90** [comment]
The file path is `/snap/nextcloud/current/config/php/php-fpm.d/` where to change those settings but the file system is read only.
To enable in write https://github.com/nextcloud-snap/nextcloud-snap/wiki/Installing-the-snap-in-writable-mode

On my testing https://github.com/nextcloud-snap/nextcloud-snap#php-memory-limit-configuration this improved a lot.
Anyway I see that is limiting allowing just nextcloud php settings and not also the web server.

**Comment by Mte90** [comment]
Looking also on the files I don't think that the settings are following the official guide to server tuning https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html
As example opcache is not enabled, just loaded.

**Comment by kyrofa** [comment]
> As example opcache is not enabled, just loaded.

[Sure it is](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/php/config/php.ini#L1767). In fact, most of the settings they recommend are the default, which is why you don't see a lot of opcache configuration there.

**Comment by Mte90** [comment]
Well the tuning documentation specify some settings for opcache that are not used in the default settings.
If we acan be able to change those settings maybe we can tune it based on the needs and be limited.
There are nextcloud hostings that use snap and give to you just the root access to the machine but you can't do anything with that as those files are in read only.

**Comment by kyrofa** [comment]
I'm afraid opening the PHP config is a footgun. Handing that to our users does not fit within the vision for this project. However, that doesn't mean that we can't fix this issue, we just need to generate a config that scales better. That [algorithm is embarrassingly simple](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/php/bin/start-php-fpm#L37-L43), any ideas for how to make it smarter?

> There are nextcloud hostings that use snap and give to you just the root access to the machine but you can't do anything with that as those files are in read only.

Haha, hosting companies are charging people money for something that we actually maintain for free? Genius.

**Comment by Mte90** [comment]
So running the algorithm on the machine where I saw all the issue that has 1 gb of ram, I get `961` that divided for `50` means `19,22`.
I set the memory limit to 500mb and now is completely different, still slow but now after all is loading. I personally think that should be like half of the ram available with a minimum of 128mb.

I think also the possibility to alter the apache conf in the snap will be helpful.

**Comment by Mte90** [comment]
I hope that doesn't get closed but reopened because needs a better algorithm to set the RAM.

**Comment by soup-in-boots** [comment]
> That [algorithm is embarrassingly simple](https://github.com/nextcloud-snap/nextcloud-snap/blob/master/src/php/bin/start-php-fpm#L37-L43), any ideas for how to make it smarter?

The calculation is mostly fine, it's just gonna run you right to the system's limit if you're at the high end of the estimates. In that case, if you ever wind up using the maximum number of children, you'll either start swapping or immediately hit OOM.

It also leaves no resources behind for other processes.

For small machines I would propose limiting yourself to ~75% of the available memory instead of all of it. That'll under-utilize high end machines, though. If you've got 64GB of RAM, you'll only allow 48GB to be used.

On the other hand, if the vision for the package is that it should be able to run on systems with 1GB of RAM or 64GB of RAM, then the added complexity of making it configurable is probably less than the complexity needed to make smart, automated decisions about memory usage. Maybe I'm wrong about that, but it is my impression. I'd personally let the end-user make an informed decision rather than try to intuit what makes sense based on the environment.

I came here because I'm dealing with an instance running on 1GB of RAM. Obviously that's a very small system, and it may not gel with the expected operating environment. It's run fine for well over a year at this point, and only began having issues this week (it's become more widely adopted across my company over time, and we have a few new hires too). 

It's definitely time to upscale my company's instance, but the guy who normally manages this system is out on vacation, and I don't want to risk breaking _everything_ in his absence. I had hoped to impose a hard limit on this setting to hold us over while he's away. Oh well.
