### ISSUE TITLE
Feature Request: Enable web server compression

### ISSUE THREAD

**Issue by malgam** [nextcloud-snap/nextcloud-snap#1297]
I have a Nextcloud snap system running behind a relatively slow ADSL connection and would really like to enable compression in the apache server to improve performance.  As far as I can tell, the relevant module (mod_deflate.so?) is not included in the snap.  Would it be possible to include this as an option?

**Comment by kyrofa** [comment]
Would there be a downside to doing this by default? I wonder is reverse proxies might have issue with it, but it needs a little research. Seems worth doing, though.

**Comment by pachulo** [comment]
I wanted to take a peek on this, but I don't really have any free time now...

I was thinking about making it optional, on by default and to adapt this Nginx configuration to Apache (from https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst):

```
# Enable gzip but do not remove ETag headers
    gzip on;
    gzip_vary on;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
    gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;
```
Which I the only “official” thing I could find back in the day.

> Seems worth doing, though.

I also think so; this is one of the prominent “Opportunities“ that Lighthouse highlights when analyzing my instance.

**Comment by kyrofa** [comment]
@pachulo do you think you'll have any time to look into this?

**Comment by pachulo** [comment]
Hey @kyrofa ! I do have some free time now, but I'm missing something before staring...where is the source of the .htaccess file on the snap repo? Or is it generated on-the-fly when the snap is built?

**Comment by kyrofa** [comment]
Yep you got it. You should be able to do this straight in the Apache config in the snap though, not mess with the .htaccess file. Am I missing something?

**Comment by pachulo** [comment]
OK, I've created a branch here: https://github.com/pachulo/nextcloud-snap/tree/features/1297/enable-web-server-compression
But I still didn't test it: will try tomorrow when builds are done: https://code.launchpad.net/~pachulo/+snap/nextcloud-snap-http-compression

**Comment by pachulo** [comment]
OK, I have a working compression snap!
But before the PR, I was guessing: should we be using `brotli_module` instead of `mod_deflate`?

It seems like it's good and old enough:
* https://cran.r-project.org/web/packages/brotli/vignettes/brotli-2015-09-22.pdf
* https://devblogs.microsoft.com/dotnet/introducing-support-for-brotli-compression/

**Comment by kyrofa** [comment]
@pachulo I don't know much about this-- are they both in the httpd codebase?

**Comment by pachulo** [comment]
Yes, they are both official modules:

- https://httpd.apache.org/docs/2.4/en/mod/mod_brotli.html (since 2.4.26)
- https://httpd.apache.org/docs/2.4/en/mod/mod_deflate.html

> I definitely favor stability over shiny.

Yeah, that's why I was guessing if [3 years and a half](https://www.apachelounge.com/viewtopic.php?p=35265) since the inclusion in Apace httpd is enough to consider it "stable".

**Comment by pachulo** [comment]
OK, I've been doing some local tests with the `brotli` compression [enabled snap](https://code.launchpad.net/~pachulo/+snap/nextcloud-snap-http-compression-brotli). As you can observe, it adds a little bit of delay to the finish times of the responses, but it saves around 66% of bytes in total!

* No compression
![image](https://user-images.githubusercontent.com/3256953/110245141-508ef200-7f62-11eb-9608-76c394c0a43a.png)
* Brotli compression 1
![image](https://user-images.githubusercontent.com/3256953/110245153-571d6980-7f62-11eb-9e3f-993d80f31278.png)

I think that it makes the more sense to be compressing as fast as we can, specially on low-end hardware (anyone who wants to tune this still can use a reverse proxy and configure whatever they want), so I've settled on the `brotli` compression level 1 for now, since it's more or less equivalent to the savings offered by `gzip 4` and performs way faster.

Here is more info regarding `gzip` vs `brotli`:
* https://blog.cloudflare.com/results-experimenting-brotli/
* https://blogs.akamai.com/2016/02/understanding-brotlis-potential.html

**Comment by pachulo** [comment]
What do you think @kyrofa ? Should I go and implement a test for this an open the PR?
