### ISSUE TITLE
MySQL Tuning

### ISSUE THREAD

**Issue by SpontaneousDuck** [nextcloud-snap/nextcloud-snap#1328]
#### Describe the bug
I am wondering what the correct way to change MySQL configurations is for the snap version. the NextCloud documentation seems to be written towards configuring the full installed one. I was unable to find a comparable ```mysql.conf``` file in the ```/snap/nextcloud/current``` directory. the reason I am doing this is my hardware is pretty low-end and MySQL is not running very well on it. I have some config values for my hardware but don't know where to put them for the snap's MySQL to take them. thanks in advance!

#### Expected behavior
Ability to config MySQL

#### OS/snapd/snap version
```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  18.0.4snap1  20500  latest/stable  nextcloud✓  -

$ snap version
snap    2.44.3
snapd   2.44.3
series  16
debian  9
kernel  4.14.150-odroidxu4
```

**Comment by kyrofa** [comment]
Thanks for logging the issue! The MySQL configuration is located at `/snap/nextcloud/current/my.cnf`, however, it is read-only due to the fact that it's contained within the snap itself, which means I don't recommend trying to tweak it. However, I'd very much like to solve #49 and have the snap automatically optimize its mysql depending on the hardware, I just don't have the knowledge to do that such that I'm confident I'm not breaking existing users. How would you feel about helping me with that?

What hardware are we talking about? What is the limiting factor? What kind of tuning would you want the snap to do?

**Comment by SpontaneousDuck** [comment]
Sure! I am currently running the server on and ODroid HomeCloud 1 which is an Exnyos 5422 Octacore Arm chip with 2GB of DDR3. I am not too sure about the limiting factor but using ```top``` every time I make a request on the web app, mysql spikes to 100% usage for a few seconds. I was referencing [OwnCloud forum](https://central.owncloud.org/t/mysql-mariadb-optimal-settings-for-running-on-raspberrypi-3-model-b/17004) where someone had taken the time to tune mySQL for a rasperry pi which is similar in performance I believe. I think the limiting factor is the SQL server is running off an SD card over the MMC interface so it is slowing down with IO. Was planning on increasing the caching since I am only using about 25% of my available RAM currently. Also maybe adding more threads since mySQL seems to peg one core only and leaves the other 7 cores running at minimal usage.

**Comment by kyrofa** [comment]
> Also maybe adding more threads since mySQL seems to peg one core only and leaves the other 7 cores running at minimal usage.

Note that `thread_concurrency` [apparently does nothing](https://www.percona.com/blog/2012/06/04/thread_concurrency-doesnt-do-what-you-expect/). In fact, [it sounds](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_thread_concurrency) like it's multithreaded by default. I wonder why it seems to only use one of your cores.

**Comment by Cylinder** [comment]
This may not just be a Pi issue.  The poor NextCloud/mySQL performance when transferring many small files is well known.
People suggest work-around hacks such as giving real accounts to NextCloud users and having them scp files to the nextcloud [server](https://www.youtube.com/watch?v=3v5T5czXTcU).
People have also suggested some unsafe modifications to the mySQL configurations to get around it: [link1](https://github.com/owncloud/core/issues/20967#issuecomment-205474772) [link2](https://help.nextcloud.com/t/very-slow-sync-for-small-files/11064)
I would like to add these hacks to my snap-nextcloud-mysql implementation which is running on an i7, because transferring many small files is very slow and makes a single mySQL thread run at 90% of a CPU.

What is the best way to modify /snap/nextcloud/current/my.cnf?  Rebuild the snap myself?  Or should I try to make an overlay file system?  If  I make an overlay, will the overlay mount before snap-nextcloud-mysql starts on boot?    
Thanks for any suggestions.

**Comment by kyrofa** [comment]
@Cylinder there is currently no supported way to change the mysql config. Note that overlays won't work for exactly the reason you outlined. Building the snap yourself is always an option, of course. I'd like to think there are improvements to be had here that are safe and benefits snap users in general, but my hopes aren't terribly high given the docs and anecdotes like yours :cry: .

**Comment by 0x41mmarVM** [comment]
@kyrofa "there is currently no supported way", but is there a possible way altogether? after a powercut I faced some HDD corruption and now mysql won't start, and as far as I know the only way to proceed is to set innodb_force_recovery=1 in my.cnf. I'm trying to mount an external directory in the snap filesystem, but it doesn't seem to be working

**Comment by 0x41mmarVM** [comment]
> 
> 
> @kyrofa "there is currently no supported way", but is there a possible way altogether? after a powercut I faced some HDD corruption and now mysql won't start, and as far as I know the only way to proceed is to set innodb_force_recovery=1 in my.cnf. I'm trying to mount an external directory in the snap filesystem, but it doesn't seem to be working

For posterity: I've managed to do it by mounting a writable directory with a copy of the snap files on the path where the snap filesystem is supposed to be
`sudo mount --bind -o nodev,ro /home/snapDuplicate /var/snap/`
But no luck, seems like my files are corrupt.

**Comment by pachulo** [comment]
I would like to investigate this. Some improvement should be accomplished after this https://github.com/nextcloud-snap/nextcloud-snap/pull/1842 but there's still room for improvement.

Are still experiencing the same problems with the latest versions @SpontaneousDuck ? What about you @Cylinder and @0x41mmarVM ?

**Comment by joolz** [comment]
Hi all,

I'm having what might be this issue. Since years I have the latest nextcloud running on a Raspberry Pi with Raspbian. There is one user (me) and I use the Pi for some calendar syncing, storing of files. Nothing special, not even on a Pi. Everything always ran smoothly. Not lightning fast, but that's OK.

Last week, on the same Pi, I installed the latest Ubuntu LTS with nextcloud  22.2.0snap2. At first I was delighted to see that I didn't have to do the whole mysql, apache, ssl, php setup manually. However, I now have frequent issues using nextcloud. Mysql can't be reached anymore (looks like https://github.com/nextcloud-snap/nextcloud-snap/issues/121), the Pi goes into CPU hog mode and from that moment on my ssh connection is dead, the web front-end times out and I have to physically disconnect the Pi.

I would like to tweak mysql.cnf but since this isn't really an option, I might have to go back to a non-snap setup. Is there a way to move all configs (especially mysql.cnf) into a "writable snap area" if such a beast exists? Or make the db configurable with an nextcloud.occ command?

Thanks,

Joolz.

**Comment by pachulo** [comment]
Hi @joolz ! Thanks for your input, let me ask some questions:

> However, I now have frequent issues using nextcloud. Mysql can't be reached anymore (looks like #121), the Pi goes into CPU hog mode and from that moment on my ssh connection is dead, the web front-end times out and I have to physically disconnect the Pi.

I'm running my instance on a somewhat similar config, using a Raspi 3 with Ubuntu 18.04, and I don't have those issues. I do have a swap partition of 1Gb configured, which I think it's what makes the thing usable.
And with the [latest changes implemented on the snap's mysql config](https://github.com/nextcloud-snap/nextcloud-snap/pull/1842), the swap partition seems to be hit less often, which makes everything a little bit smoother.

> I would like to tweak mysql.cnf but since this isn't really an option, I might have to go back to a non-snap setup. Is there a way to move all configs (especially mysql.cnf) into a "writable snap area" if such a beast exists? Or make the db configurable with an nextcloud.occ command?

Here my questions is, which changes would you implement?
The thing I would like to try is[ if is worth to dynamically tune `innodb_buffer_pool_size` and other related parameters](https://github.com/nextcloud-snap/nextcloud-snap/issues/49#issuecomment-851694866). Do you have any experience touching those (or others)?

**Comment by joolz** [comment]
Hi @pachulo,

Thanks for the quick response!

I've been running the machine without any swap, maybe a bad habit but so far it worked. Anyway, I just setup a swap of 1G, following your example. Let's hope this fixes it :)

And about the changes I would like to implement... That's hard to say. First a disclaimer: I'm familiar with Linux in general, but hardly with Snap, so excuse me if I say anything stupid.

Normally when I hit an issue like this, I try to locate where the cause of the issue lies. Since NC has always run nicely on the same hardware, I assumed it was the Snap, of something configured in the Snap that causes the problem. When I googled it, I found that others suggested finetuning mysql.cfg. This might or might not be a solution (if it were possible). But it might also be something else... So generally I would find it convenient to be able to change all the settings for anything in the Snap (apache, php, redis, mysql, nextcloud) to be able to troubleshoot and to finetune. 

But then this might not be the intention of the Nextcloud Snap.

I will let you know if adding swap solved my problem, thanks again!

Joolz.

**Comment by joolz** [comment]
Hi @pachulo,

With a 1G swap file all works nicely. I can generate previews of folders with images totalling 200M+. Lots of calls to php-fpm, but the system doesn't collapse, it just gets slower which is only normal. Memory use is also stable under heavy load (opening 10 webpages simultaniously, every one containg some 50 10M images without existing previews)

              total        used        free      shared  buff/cache   available
Mem:          908Mi       522Mi        37Mi        18Mi       348Mi       345Mi
Swap:         1.0Gi       407Mi       616Mi

Before the swapfile, generating previews and scrolling through calendar pages were the evildoers, and both now work fine. Thanks!

About the possibility to finetune the config of all the applications in the snap, although I don't need it right now, I think it would be a good thing to have. Something analog to /etc, but for the snap. Again, I'm not familiar with snaps, so this might be against the snap pilosophy and I happily leave this to the people who do know what they are talking about :)

Joolz.
