### ISSUE TITLE
Error: Your data directory is readable by other users |  Data change to external 

### ISSUE THREAD

**Issue by Marco913** [nextcloud-snap/nextcloud-snap#1398]
I have installed nextcloud via snap, made my data location to `/media/usbhd/(data)` , made the changes 

`sudo nano /etc/fstab`
`/dev/sda1 /media/usbhd ntfs defaults 0 1`
`sudo chown -R root:root /media/usbhd`
`sudo chmod -R 0770 /media/usbhd`

but still I get the message :

_"Your data directory is readable by other users
Please change the permissions to 0770 so that the directory cannot be listed by other users."_

apparently nobody else has the problem as I have seen, at least not about snap installation

**Comment by kyrofa** [comment]
Yeah it looks like you're doing the right thing. Can we see the output of `sudo nextcloud.occ config:list`?

**Comment by Marco913** [comment]
this is the output of: `sudo nextcloud.occ config:list`

Your data directory is readable by other users
Please change the permissions to 0770 so that the directory cannot be listed by other users.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /snap/nextcloud/21799/htdocs/lib/private/Console/Application.php:168
Stack trace:
#0 /snap/nextcloud/21799/htdocs/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /snap/nextcloud/21799/htdocs/occ(11): require_once('/snap/nextcloud...')
#2 {main}

**Comment by kyrofa** [comment]
Well that was useless. Can you look at `/var/snap/nextcloud/current/nextcloud/config.php` and tell me what your `datadirectory` is set to?

**Comment by Marco913** [comment]
i have set the datadirectory to `'datadirectory' => '/media/usbhd/data'`

the strange thing is that when i was logged in it was still working and my HD was detected but when i logged out i got this message and did not come back in

**Comment by Leptopoda** [comment]
@Marco913 still a problem?
What does ```ls -l /media/usbhd ``` say?

**Comment by kyrofa** [comment]
Terribly sorry for this dropping off my radar, but yeah give @Leptopoda's command a test.

**Comment by javimosch** [comment]
I'm having the same issue.
ntfs do not support linux rights, maybe that's why?

**Comment by mikebakke** [comment]
That is exactly why - I hit this today because one of my disks is an old legacy NTFS HD and it dropped off the system overnight. My FSTAB uses the "permissions" option but when I manually mounted I did not and hit the issue.

mount /dev/disk -o permissions /mnt/mountpoint 

fixed it for me just now...

must move that to ext-4 (some day)

**Comment by d-popov** [comment]
I had the same issue and no combination of chown and chmod was able to make nextcloud happy.
It turns out there's a way to disable this "Error". And quite frankly, it may be good for security, but if we are self hosting it, it should be our decision, and not an error.
Add this setting in the config.php
`'check_data_directory_permissions' => false`
And you can access your nextcloud again :)

**Comment by kyrofa** [comment]
Huh I didn't know about that option, thanks for sharing!

**Comment by walmer26** [comment]
> I had the same issue and no combination of chown and chmod was able to make nextcloud happy. It turns out there's a way to disable this "Error". And quite frankly, it may be good for security, but if we are self hosting it, it should be our decision, and not an error. Add this setting in the config.php `'check_data_directory_permissions' => false` And you can access your nextcloud again :) no messy fstab, chown, chmod magic needed.

Thank you!!!! This was very straight forward, for me this was the solution. Thank you again.

**Comment by kyrofa** [comment]
Warning: please don't use this unless you truly understand what you're doing.

**Comment by h0m3** [comment]
> I had the same issue and no combination of chown and chmod was able to make nextcloud happy. It turns out there's a way to disable this "Error". And quite frankly, it may be good for security, but if we are self hosting it, it should be our decision, and not an error. Add this setting in the config.php `'check_data_directory_permissions' => false` And you can access your nextcloud again :) no messy fstab, chown, chmod magic needed.

Thank you,

I'm running under an SMB share, so permissions are 1 totally irrelevant and 2 extremelly hard to manager. So having a screen "Your data directory is readable by other users." is not the ideal solution for my problem.

I was scouring the internet on how to trick my OS to report 750 because the permission on the client is not the same as on the host and thers no umask for cifs.
