### ISSUE TITLE
Whiteboard not working in nextcloud snap 22.2.0 Ubuntu 20.04x64

### ISSUE THREAD

**Issue by jupsoleil** [nextcloud-snap/nextcloud-snap#1768]
Hello, see https://help.nextcloud.com/t/nc-21-whiteboard-integration-error/109462 .  According to mueller: "Hello the fact is and the solution:You need min. nodejs 10 installed and min. gcc 7.3 then the whiteboard is running."

Now we get:
"Spacedeck request connection error : cURL error 7: Failed to connect to localhost port 9666: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html 6) for http://localhost:9666/api/spaces 3"

**Comment by NathanD19** [comment]
Getting the same error on my snap installation.

`
[ERROR] Spacedeck is unreachable, it might not be running. cURL error 7: Failed to connect to localhost port 9666: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:9666/api/spaces
`
AND
`
Spacedeck  request connection error : cURL error 7: Failed to connect to localhost  port 9666: Connection refused (see  https://curl.haxx.se/libcurl/c/libcurl-errors.html) for  http://localhost:9666/api/spaces
`

**Comment by szaimen** [comment]
Are you running the snap on x64? If not thats probably the reason why it doesn't work. See https://help.nextcloud.com/t/nc-21-whiteboard-integration-error/109462

**Comment by jupsoleil** [comment]
Ubuntu 20.04 and 18.04, both 64 bit.

**Comment by jupsoleil** [comment]
Hi, any news on this please?

**Comment by kyrofa** [comment]
No, I'm afraid I have very little time to debug individual apps, but definitely willing to review.

**Comment by jupsoleil** [comment]
meanwhile nextcloud v21.0.3, but unfortunately also not working :-).

**Comment by abhinav-TB** [comment]
I am facing the same issue any updates

**Comment by cue108** [comment]
I am facing error messages in Logging like:
`[ERROR] Spacedeck is unreachable, it might not be running. cURL error 7: Failed to connect to localhost port 9666: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:9666/api/spaces`

I am running Nextcloud 22.2.3 as Docker

The whiteboard opens and when I try to upload any picture or media it never finishes and I get the error in Logging.

Now the wired thing is when I check via "Connected Accounts" and click the "Spacedeck whiteboard integration" it says everything is fine...

I observed this behavior since Version 20.

Maybe one day will be  the day I will finally see embedded media files on the whiteboard.

**Comment by kyrofa** [comment]
> I am running Nextcloud 22.2.3 as Docker

I'm afraid you're in the wrong place, this repo is for the snap. Sounds like this is an issue outside of the snap, so I suggest logging this upstream.

**Comment by jupsoleil** [comment]
@kyrofa please don't close this issue - Whiteboard still doesn't work in the snap!

**Comment by kyrofa** [comment]
@jupsoleil it seems like it doesn't work in a number of places though, not just the snap. This isn't the snap's fault, and thus it serves no purpose to track it here.
