### ISSUE TITLE
Upgrade NextCloud 22.2.5

### ISSUE THREAD

**Issue by stondino00** [nextcloud-snap/nextcloud-snap#2001]
Released on changelog page

**Comment by stondino00** [comment]
Updated on the blog as well and is officially their next release.

**Comment by NaXal** [comment]
**Big scare after 22.2.5 Snap1 Auto update**

Hello,

I have been running NextCloud on my dedicated hardware at home for last several months. Things were going smooth, all snap auto updates were smooth, no issues at all. But this 22.2.5snap1 auto update broke my NextCloud installation and I am unable to get it back working.

Setup Information,

Hardware :- Acer Laptop, Intel Pentium Quad Core N3530, 4GB DDR3, 500GB HDD, Internet via Ethernet.
Software :- Ubuntu Server 20 LTS (up to date), NextCloud Snap (Default installation, nothing extra), Let's Encrypt Key Files installation via Snap SSL install Commands.

Issue :- Web Interface is broken, like CSS or HTML is completely messed up.

Troubleshooting :- I have immediately tried to revert back, using snap revert command, which took nextcloud back to snap3, but web interface is still broken. I have tried to clear browser cookies and data and reboot the server multiple times, but it's still serving a broken page. 

I have once again tried the manual command for snap refresh, it happens successfully but web interface is still broken. NextCloud is logging in the users but the web pages are unusable with their broken layout. I have restarted the server, checked to make sure server load is fine, but still the web pages are broken.

**Auto Fix ** 

As I was typing this post to request some help, I did multiple reboot of the server. Not sure how or what did the trick, all of a sudden, after one of this random reboot, the web page fixed it self and started to work fine.

Thanks.

**Comment by kyrofa** [comment]
Garbled assets are not actually unusual. This is something that the Nextcloud Fixer generally takes care of, but it may not have had a chance to run until the "random reboot" that you describe. Any chance you still have logs?

**Comment by NaXal** [comment]
Hello,

Thanks for the reply and putting some sense into the issue. I guess unluckily the update happened perhaps right before I logged in, so I guess that fixer thing didn't complete it's task. But as an end user, I had no clue since the notification up top was reporting successful update happened.

Incident happened on late morning of 14th March (IST) and I am sorry, I think the log file (NextCloud -> Settings -> Logs -> Download Logs) isn't going back that far.

Still I am attaching the file for your investigation.

Thanks.
[nextcloud.log](https://github.com/nextcloud-snap/nextcloud-snap/files/8250611/nextcloud.log)
