### ISSUE TITLE
Problem with Netxcloud 23.0.2snap1 - The Files page remains empty

### ISSUE THREAD

**Issue by versus167** [nextcloud-snap/nextcloud-snap#2022]
#### Describe the bug

The Files page in browser remains empty.

#### To Reproduce
1. Go to '...index.php/apps/files/#'

#### Expected behavior

This should display the files

#### Screenshots

![Bildschirmfoto von 2022-03-16 15-37-52](https://user-images.githubusercontent.com/3191327/158617019-69e76b72-30ca-4765-ba14-4477ad042b84.png)

#### OS/snapd/snap version

Ubuntu 20.04.4 

    $ snap list nextcloud

snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  23.0.2snap1  29929  latest/stable  nextcloud✓  -

and:

    $ snap version

snap version
snap    2.54.4
snapd   2.54.4
series  16
ubuntu  20.04
kernel  5.4.0-104-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
(output was to big to paste here...)

[issues.log](https://github.com/nextcloud-snap/nextcloud-snap/files/8263621/issues.log)

**Comment by kyrofa** [comment]
Huh, that also looks healthy. Do you see any javascript errors in the console?

**Comment by versus167** [comment]
Now I tried it with Chrome on Linux (before with Firefox on Linux). With Chrome no problem...

With Firefox on Win10 -> no Problem. I think my Firefox is the problem.

**Comment by versus167** [comment]
Okay - I cleared Firefox's cache and now it works.  Thanks for your patience

**Comment by kyrofa** [comment]
Hey good deal! That's a bit frustrating, I'm sorry, but I'm glad you got it sorted!

**Comment by NaXal** [comment]
Hello,

Continuing to the previous issue, https://github.com/nextcloud-snap/nextcloud-snap/issues/2001#issuecomment-1067600172 I have again run into the broken web page issue after the 23.0.2snap1 update.

This time around I have waited half a day but the pages aren't fixed yet.

Surprisingly, the issue is now seems to be limited to mobile browsers only. Since I am able to access NextCloud properly when using a desktop browser. I have restarted the server in between, just hoping like last time, if that helps, but no, it is not fixing it self.

I am attaching the log. If possible, please look into it as advice me how do I fix the issue?

Thanks.
[nextcloud.log](https://github.com/nextcloud-snap/nextcloud-snap/files/8286238/nextcloud.log)
