### ISSUE TITLE
Space hungry

### ISSUE THREAD

**Issue by alkonaesc** [nextcloud-snap/nextcloud-snap#2094]
Hi!

I am really confused about 1 thing. I serve some of my photos/books on the server. In total 160gb is occupied with files, however I notices that 1TB disk is almost full (700gb busy). 

Is there any info how I should clean snap logs etc? 
I tried to get in folders but got "permission denied" everywhere.

**Comment by Refhi** [comment]
Hi,

may I suggest you take a look to where the accessible files (you need root access) are ? => https://github.com/nextcloud-snap/nextcloud-snap#where-is-my-stuff

otherwise you might be familiar with baobab or `du -hs *` to check where the bloated folders are ?

I never had to clean humongous log files in this snap, there might be another issue ?

**Comment by scubamuc** [comment]
check Nextcloud-snap disk udsage:
`sudo du -hs /var/snap/nextcloud/common/nextcloud/data`

find largest files in nextcloud-snap directory:
`sudo find /var/snap/nextcloud/common/nextcloud/data -type f -printf "%s\t%p\n" | sort -n | tail -5 `

clear nextcloud-snap log:
`sudo rm /var/snap/nextcloud/common/nextcloud/data/nextcloud.log`
