### ISSUE TITLE
Sometimes 100% CPU usage until restart

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2119]
#### Describe the bug
Sometimes (~ every second day?) the CPU usage is up to 100% for whatever reason. Very much does mysql in combination with php-fpm use. This completly slows down the whole nextcloud instance with a factor of ~0.25.
After a restart of the snap package with `sudo snap restart nextcloud` this problem doesn't get solved. Only a full restart of the whole server does help.
Any idea why this could be?

#### Screenshots
![grafik](https://user-images.githubusercontent.com/23138465/178965677-cc124581-9243-4c04-ba2d-99eff0067ba7.png)

#### OS/snapd/snap version
Ubuntu Server 19 arm64

Output of $ snap list nextcloud
```
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  24.0.1snap1  31037  latest/stable  nextcloud✓  -
```

Output of $ snap version
```
snap    2.56.2
snapd   2.56.2
series  16
ubuntu  20.04
kernel  5.4.0-1045-raspi
```

#### Logs
More logs I will add soon, when it happens again...
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by scubamuc** [comment]
does your issue take place regularly at certain times every two days?
-- use `sysstat` to log and check intervals
maybe you can narrow down what the reason is for cpu-steal

![grafik](https://user-images.githubusercontent.com/54933878/179351655-c6473e33-da9b-4fe0-9ae2-bd8f2a3ff14b.png)

php-fpm tends to steal cpu but only for a few seconds... never reaching 100% 
if you're running on a raspi, check `%iowait`, this could mean that your Memory-Card is failing

**Comment by Pilzinsel64** [comment]
Thank you for your answer! Will try your two suggestions and come back soon. ^^

Since last weekend it happened three times. But since two days it didn't happen again. I didn't even regonize it before last weekend.

Just saying, the SD card isn't even mounted for me after booting. I'm primary using an SSD drive via USB and the SD card is only used during the fist few seconds of the initial boot (can't boot without for some reason).
