### ISSUE TITLE
Question: Installing Extra Mods (mod_geoip for GeoIP Block)

### ISSUE THREAD

**Issue by gaia** [nextcloud-snap/nextcloud-snap#2135]
To have Apache drop requests from country ranges, one popular option is mod_geoip, such as
https://www.cloudbooklet.com/how-to-setup-geoip-block-using-apache/

How to use this mod (and it will probably applies to installing any other mod) when Apache is snap packaged?

PS I've tried to avoid snaps until using the Nextcloud snap. It beats Docker hands down. Thank you!

**Comment by scubamuc** [comment]
agreed, Nextcloud-snap ist top!
there is no easy way to mod Apache in snap...
use Geoblocker App instead:

![grafik](https://user-images.githubusercontent.com/54933878/180733843-ec8caed5-b6f3-4022-9e24-0d2ed17963e8.png)


![grafik](https://user-images.githubusercontent.com/54933878/180733753-056e7e8b-2753-4a55-9dcd-15fc154e3664.png)

**Comment by kyrofa** [comment]
> How to use this mod (and it will probably applies to installing any other mod) when Apache is snap packaged?

The snap gains its simplicity because it bundles everything within it, and doesn't contain a lot of knobs. There's actually no way to install Apache modules that aren't already included in it, and I'm afraid mod_geoip isn't included. I'm sorry, if you want to use this snap you'll need to find another solution for geo blocking (like the app that @scubamuc recommended).
