### ISSUE TITLE
When trying to sync files using the Desktop Client for Windows 10 (Version 3.5.4) I am getting this error: "Server replied with an error while reading directory [Directory Name]: connection closed.

### ISSUE THREAD

**Issue by ClearAl** [nextcloud-snap/nextcloud-snap#2165]
#### Describe the bug
When trying to sync files using the Desktop Client for Windows 10 (Version 3.5.4) I am getting this error: "Server replied with an error while reading directory [Directory Name]: connection closed.

#### To Reproduce
Share files to my user
Tell desktop client to sync those files.

#### Expected behavior
This does not happen on all clients but its happening on 6-8

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud : nextcloud  24.0.3snap1  31222  latest/stable  nextcloud✓  -
and:
    $ snap version : snap    
2.56.2
snapd   2.56.2
series  16
ubuntu  20.04
kernel  5.4.0-125-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).  Attached, too large for a to be a comment.
[Nextcloud_Output.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/9456989/Nextcloud_Output.txt)

**Comment by lecramed0** [comment]
Hopefully not just increasing the noise here, but wanted to add this anecdote somewhere in case it helps, and this issue seems most similar in the snap repo.

**Previous working setup:**

- local external storage folder set up with only one user (group manager) in the "Available for" box
  - only one top level directory in this storage but many sub-folders and files
- shared this top-level directory with the other users intended to have access via the Nextcloud sharing tools

The `24.0.6snap1` update breaks this configuration. All users except the group manager listed as the "Available for" user get inconsistent access to the share regardless of share permissions. Either directory connection closed errors as above or `500 Internal Server Error` on modifying certain files/folders by the sync clients on Windows (tested on 3.4.1 & 3.6.0).

- group manager access is unaffected and other users still pull down any new files added
- shared folders not located on an external storage behave as expected.

**New working setup:**

- add all necessary users as a group to the "Available for" box in the external storage setup
- remove prior sharing of the top-level directory

While this is OK for my current requirements I'm not sure if it's desirable for all setups. I think I originally set it up this way so that I could add additional top-level directories to the external storage without giving privileges to additional users.
