### ISSUE TITLE
Security hole with external_storage

### ISSUE THREAD

**Issue by curiousmitchell** [nextcloud-snap/nextcloud-snap#2198]
Wow - just found a massive security hole. When enabling connections outside of the snap sandbox files:
$ sudo snap connect nextcloud:removable-media

the Nextcloud snap can access _every_ file on my computer as root. Happy days hacker! Now, all that's required is for someone to guess my password in order to access everything...

#### To Reproduce
Steps to reproduce:
1. Enable removable media
$ sudo snap connect nextcloud:removable-media

2. Enable External Storage in Nextcloud, setting default folder to 'local' and location to '/'
3. Have fun accessing everything on your computer.

#### Expected behavior
Generally? Not giving any program, user, or script full root access. Its a bad idea... I would expect to be able to tell the Snap what I want it to access, and only have it access that.

#### OS/snapd/snap version
I'm running Archlinux. Nextcloud snap version 24.0.4snap1 
Snap version 2.57.1-2
Kernel 5.19.9-arch1-1

**Comment by curiousmitchell** [comment]
Ok - solved it. Apparmor is beautiful. One of the great things about Archlinux is installing everything from scratch. One of the sucky things about Archlinux is also installing everything from scratch - missed apparmor. Not that I've installed and configured this, the sandbox is working as expected. While I still need to access folders as root, as this is now sandboxed that's not really an issue.

**Comment by kyrofa** [comment]
Good work. Yes, the two primary confinement techs beyond the basic things like cgroups are apparmor and seccomp filters. Sadly all of those things are OS-specific, not snapd-specific, so depending on what distro you're on and how you have it configured, snapd will be perfectly happy running things virtually unconfined. It's really awful, honestly. It's entirely unclear to end users that they're actually running services unconfined as root.

I prefer to pretend that snapd only runs on Ubuntu, because only there is the confinement story proper out of the box. Be very careful, you might want to run Nextcloud another way if you're using something other than Ubuntu.

**Comment by scubamuc** [comment]
> While I still need to access folders as root, as this is now sandboxed that's not really an issue.
maybe you could: Enable External Storage in Nextcloud, setting  location to '/' as 'sftp' for your user only
![grafik](https://user-images.githubusercontent.com/54933878/195553870-699a5750-7431-4e7b-a0f3-758ffbda906b.png)

**Comment by kyrofa** [comment]
I wrote a [wiki entry](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) about why we recommend (and can only support) Ubuntu if you're running snaps, in case you're curious. And with that, I consider this issue closed. Feel free to continue discussions, of course.
