### ISSUE TITLE
Seeking some basic information about Nextcloud snap

### ISSUE THREAD

**Issue by dln949** [nextcloud-snap/nextcloud-snap#2319]
Hi, I”m trying to learn about the Nextcloud snap, I have some questions, but can’t find any documentation that addresses them.  I don’t see an area here for mere discussion, so I hope it is okay that I post these questions here.  

1.	Once the snap package is installed, I’m not clear on the updating process:  Will updates to the snap package be only for updates to Nextcloud itself, and nothing else?  Meaning, when other components – MySql, PhP, etc. – have updates, I have to manage the updates for those separately?  Or, will there be an update for the snap package no matter which component is changing?  

2.	What are the special steps, if any, I need to follow when upgrading the LTS version of Ubuntu?  

3.	Does using the snap package for Nextcloud restrict the Nextcloud apps that can work?  

4.	I need to use these Nextcloud apps, should I expect them to work with the Nextcloud snap package:  Calendar, Tasks, Contacts, 
Files, Music, Notes, OnlyOffice

5.	Will various android apps that synchonise with Nextcloud – e.g., DavX5 – work fine with a snap installation of Nextcloud?  

6.	What is the typical lag between an upgrade to the stable Nextcloud version and the snap package being updated?  

7.	Are there any other drawbacks/limitations to using the snap package approach versus other methods of installing Nextcloud?

**Comment by kyrofa** [comment]
Using the issue tracker for questions is perfect. Welcome!

> 1. Once the snap package is installed, I’m not clear on the updating process: Will updates to the snap package be only for updates to Nextcloud itself, and nothing else? Meaning, when other components – MySql, PhP, etc. – have updates, I have to manage the updates for those separately? Or, will there be an update for the snap package no matter which component is changing?

The snap contains all of its dependencies, including mysql, php, and so on. Whenever any component needs to update, whether that is Nextcloud itself or one of those dependencies, a new snap revision is published, and your installation will automatically update.

> 2. What are the special steps, if any, I need to follow when upgrading the LTS version of Ubuntu?

You mean you have an Ubuntu LTS installed on your server, how do you update it to the next LTS without disturbing the snap installation? You shouldn't have to do anything special-- update the normal way. Snapd might be updated, but all your installed snaps and their data won't be effected at all.

> 3. Does using the snap package for Nextcloud restrict the Nextcloud apps that can work?

Not artificially, but the snap is confined. As a result, if you try to install an app that assumes you have something available on  your system but the snap isn't able to access what it's looking for, then that app may not work.

> 4. I need to use these Nextcloud apps, should I expect them to work with the Nextcloud snap package: Calendar, Tasks, Contacts, Files, Music, Notes, OnlyOffice

I can vouch for calendar, contacts, and files, but you'll need to take it for a test drive to see if the others work to your satisfaction. I know the office apps have some trouble both in and out of the snap, so your mileage may vary there. @scubamuc is the expert, there.

> 5. Will various android apps that synchonise with Nextcloud – e.g., DavX5 – work fine with a snap installation of Nextcloud?

I haven't used that particular app, but yes, all the mobile webdav apps I've tried work fine.

> 6. What is the typical lag between an upgrade to the stable Nextcloud version and the snap package being updated?

It depends on the version. For patch and minor versions, maybe a few days. For major versions, though, we generally wait until the point release to even bother testing them.

> 7. Are there any other drawbacks/limitations to using the snap package approach versus other methods of installing Nextcloud?

It probably depends on who you ask. There are three primary drawbacks from my perspective:

1. Ubuntu is really the only supported host distribution. Snaps run elsewhere, but not properly.
2. The snap is confined. This is a pro in that it makes running it pretty darn safe, but it's a con if your use-case is such that you need to break outside of that box.
3. Similar to (2), the snap isn't very flexible. It specifically targets the home or small office user, and in an effort to make it as trivial to install and use as possible, there aren't very many knobs for you to turn. Want to use postgresql instead of mysql? The snap doesn't support that. Want to make nextcloud highly-available and redundant? Sorry, the snap doesn't support having multiple web frontends talking to the same backend.

**Comment by dln949** [comment]
Thanks very much, you answered all my questions.

**Comment by scubamuc** [comment]
> I need to use these Nextcloud apps, should I expect them to work with the Nextcloud snap package: Calendar, Tasks, Contacts,
Files, Music, Notes, OnlyOffice

all mentioned apps work fine, including onlyoffice. 
https://nextcloud.com/blog/how-to-install-onlyoffice-in-nextcloud-hub-and-new-integration-feature/

> Are there any other drawbacks/limitations to using the snap package approach versus other methods of installing Nextcloud?

nothing that could break your productive work flow. Even in a corporate environment Nextcloud-snap has proven most reliable, efficient and safe. 

https://scubamuc.github.io/
