### ISSUE TITLE
Questions about the snap version of Nextclou

### ISSUE THREAD

**Issue by dln949** [nextcloud-snap/nextcloud-snap#2326]
Hi, I am new to the snap version of Nextcloud - pretty new to Nextcloud in general - I just installed the snap version of Nextcloud.  There are a few things I can't understand:  

1. Following instructions, I did the "Lets Encrypt" thingy (sudo nextcloud.enable-https lets-encrypt) - not exactly sure what that does for me, I _think_ it associates a trusted certificate with my Nextcloud server - but I'm not clear on how long that will last.  I've read that people need to do something with something called "certbot" in order to automatically renew this certificate.  Will my Let's Encrypt certificate expire at some point and I will manually need to keep renewing it?  (How?)  
2. I wish to connect my android calendar with the calendar on Nextcloud.  From what I've read online, the path to my calendar is this:  https://my.url/remote.php/dav/files/MyNextcloudUserName/ .  Do I use that same path even though I have the snap version of Nextcloud?  I don't fully understand snap packages' structures, but I thought everything is "contained" within the snap directories, so that makes me think that I need to use a different path for things like connecting calendars, tasks, contacts, etc.  
3. I have installed Nextcloud's Music app on my Nextcloud server.  But, I'm not finding a similar app for playing videos.  Am I missing that, might it be called something I'm not thinking of?  
4. I can't figure out how to display the weather conditions on the main page of the dashboard.  I have set a location and marked it as my (only) favorite, but no weather conditions ever appear, all I see is what is in the attached screenshot, it jsut says "Set Location for Weather", which I've already done.  

![Screenshot from 2023-02-22 09-49-17](https://user-images.githubusercontent.com/8601150/220679227-19b53c60-a69e-461f-94a4-fa7685063f8a.png)

**Comment by kyrofa** [comment]
Hey there, welcome! Happy to help.

> 1. Following instructions, I did the "Lets Encrypt" thingy (sudo nextcloud.enable-https lets-encrypt) - not exactly sure what that does for me, I think it associates a trusted certificate with my Nextcloud server - but I'm not clear on how long that will last. I've read that people need to do something with something called "certbot" in order to automatically renew this certificate. Will my Let's Encrypt certificate expire at some point and I will manually need to keep renewing it? (How?)

Right, it sets you up with a certificate signed by Let's Encrypt such that you can use HTTPS, which is always recommended. Now that you've done that, the snap will keep the certificate up to date for you, so you don't need to worry about renewing it as long as the snap is running.

> 2. I wish to connect my android calendar with the calendar on Nextcloud. From what I've read online, the path to my calendar is this: https://my.url/remote.php/dav/files/MyNextcloudUserName/ . Do I use that same path even though I have the snap version of Nextcloud? I don't fully understand snap packages' structures, but I thought everything is "contained" within the snap directories, so that makes me think that I need to use a different path for things like connecting calendars, tasks, contacts, etc.

Yes, the snap doesn't change anything in that regard.

> 3. I have installed Nextcloud's Music app on my Nextcloud server. But, I'm not finding a similar app for playing videos. Am I missing that, might it be called something I'm not thinking of?

I personally am not sure, that might be a question for help.nextcloud.com where you'll get access to more Nextcloud folks.

> 4. I can't figure out how to display the weather conditions on the main page of the dashboard. I have set a location and marked it as my (only) favorite, but no weather conditions ever appear, all I see is what is in the attached screenshot, it jsut says "Set Location for Weather", which I've already done.

I'm afraid this is also a question for the upstream Nextcloud folks. I personally disable that app, so I have no idea how it works.

**Comment by scubamuc** [comment]
Hi and congratulations,

> 2. I wish to connect my android calendar with the calendar on Nextcloud. From what I've read online, the path to my calendar is this: https://my.url/remote.php/dav/files/MyNextcloudUserName/ . Do I use that same path even though I have the snap version of Nextcloud? I don't fully understand snap packages' structures, but I thought everything is "contained" within the snap directories, so that makes me think that I need to use a different path for things like connecting calendars, tasks, contacts, etc.

you'll need an app called davx5 ([your favourite app store](
https://f-droid.org/en/packages/at.bitfire.davdroid/
)) to sync your calendar and contracts to your mobile device, see here https://www.davx5.com/tested-with/nextcloud its fairly simple and self explanatory. there are plenty videos and how-to's out there.

you'll find the calender path in your calender settings:
![grafik](https://user-images.githubusercontent.com/54933878/220712886-d1229e37-6a17-42b6-91ac-15d8c74ecfd2.png)

> 3. I have installed Nextcloud's Music app on my Nextcloud server. But, I'm not finding a similar app for playing videos. Am I missing that, might it be called something I'm not thinking of?

you'll need to take a look around for a music or video app for Nextcloud... you'll need an app that can utilise webdav. possibly the kodi app for android could do that ([your favourite app store](
https://f-droid.org/de/packages/org.xbmc.kodi/
)). Nextcloud will not replace a media server though. you may consider installing [Plex server](https://snapcraft.io/plexmediaserver) for music and videos

> 4.I can't figure out how to display the weather conditions on the main page of the dashboard. I have set a location and marked it as my (only) favorite, but no weather conditions ever appear, all I see is what is in the attached screenshot, it jsut says "Set Location for Weather", which I've already done.

I don't use the weather app myself either... but I believe there has been a change upstream because most weather providers require signed app-keys, so you'll have to register for that. There are some fun ways to integrate weather forecasts into your Nextcloud bar having a window to see what the weather is like :-)

![grafik](https://user-images.githubusercontent.com/54933878/220711325-566d3955-bd72-4392-968e-0d7e300de651.png)
