### ISSUE TITLE
Upgrade to "Ubuntu Pro" or not? 

### ISSUE THREAD

**Issue by anibtro** [nextcloud-snap/nextcloud-snap#2331]
What is your opinion on upgrading to "Ubuntu Pro"?
I'm running NC Snap on a dedicated small home server (private purpose only) without any issues so far and am wondering about the pro's and con's. 
Thanks for your thoughts on this.

**Comment by kyrofa** [comment]
This question isn't really related to the snap-- you might consider asking it on AskUbuntu, for example, where you will get more Ubuntu-centric answers. That said, I'm happy to share my brief opinion as, it turns out, I helped create Ubuntu Pro.

Given that you can get 5 free subscriptions, there's really no downside. It's supported for 10 years instead of 5, and you get security patches for Universe as well as Main. Given that it's new, the only potential downside is that the security team doesn't end up doing a terribly good job of keeping up with updates to LTS releases after 5 years, despite Ubuntu Pro claiming that they will. That remains to be seen, but in my experience, the Ubuntu Security team has some solid folks.

**Comment by scubamuc** [comment]
"Ubuntu Pro" is a great service if you have an Ubuntu-one account already. 

**advantages:**
- 5 free subscriptions for private use 
- Kernel Livepatch to avoid unscheduled reboots
- covers containers on LXD host
- added security for internet facing servers  
- peace of mind
- easy to set up and manage

personally I'd upgrade LTS nonetheless

**Comment by kyrofa** [comment]
**Disadvantages:**

- Stuck on old versions of software (even ESM generally abides by the SRU process)

**Comment by kyrofa** [comment]
> - Kernel Livepatch to avoid unscheduled reboots

Note that livepatch isn't required in order to use Ubuntu Pro. I've never personally enabled this as people I respect view it as a hack.

> - covers containers on LXD host

Are you saying enabling Ubuntu Pro on the host will automatically enable it for LXD containers running on that host? That's news to me-- where are you getting this?

**Comment by scubamuc** [comment]
oops, you're right... wrong column!
https://ubuntu.com/pricing/pro
i have noticed the 'ESM' messages have disappeared in my containers though...

**Comment by kyrofa** [comment]
This seems relevant and more in-line with my understanding:

> * Any of: KVM | Qemu | Boch, VMWare ESXi, LXD | LXC, Xen, Hyper-V (WSL, Multipass), VirtualBox, z/VM, Docker. All Nodes in the cluster have to be subscribed to the service in order to benefit from the unlimited VM support

**Comment by scubamuc** [comment]
agreed, I've edited my post...
