### ISSUE TITLE
Unable to attach local storage to Nextcloud snap app

### ISSUE THREAD

**Issue by scotrod** [nextcloud-snap/nextcloud-snap#2409]
Hello. I am following this guide: https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition to attach NFS share which is mounted to my Ubuntu VM to NC which was installed via snap
After completing all the steps from section "If you have already created an admin user" I am getting the following error message:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

What logs should I search for in order to troubleshoot this? I am a first timer with NC, and honestly it's way too overwhelming to attach a single folder to this app. I don't even know where should I start troubleshooting.

**Comment by scubamuc** [comment]
no need to be overwhelmed, you're on the right track

see [logging an issue ](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)

more about [Nextcloud-snap logs](https://github.com/scubamuc/scubamuc.github.io/blob/scubamuc/wiki-md/NEXTCLOUD.snap_logs.md)

**Comment by scubamuc** [comment]
take a deep breath, relax and try to explain more clearly what you are trying to do and what you've done so far. try to recollect your steps taken and list them one by one to see if you've missed anything.

from what I understand, you've tried to change your Nextcloud data-directory... not to another partition, but to an NFS-share on another machine? If this is the case, we'll need to know if the NFS-share is mounted correctly, with the correct permissions and to the correct directory for Nextcloud-snap to connect to. 

according to the above mentioned documentation to either `/media` or `/mnt` as root with root permissions.
- where is the NFS-share being mounted to on the Nextcloud VM: 
  show  `cat /etc/fstab`
- did you connect the removable-media plug as mentioned in the [README](https://github.com/nextcloud/nextcloud-snap/blob/master/README.md) in order to grant the snap permission to access external drives.
- also show `sudo cat /var/snap/nextcloud/current/nextcloud/config/config.php | grep 'directory'`

@kyrofa this should be possible theoretically, but I haven't tried mounting an NFS-share?

**Comment by kyrofa** [comment]
Yeah me neither.

**Comment by scotrod** [comment]
> take a deep breath, relax and try to explain more clearly what you are trying to do and what you've done so far. try to recollect your steps taken and list them one by one to see if you've missed anything.
> 
> from what I understand, you've tried to change your Nextcloud data-directory... not to another partition, but to an NFS-share on another machine? If this is the case, we'll need to know if the NFS-share is mounted correctly, with the correct permissions and to the correct directory for Nextcloud-snap to connect to.
> 
> according to the above mentioned documentation to either `/media` or `/mnt` as root with root permissions.
> 
>     * where is the NFS-share being mounted to on the Nextcloud VM:
>       show  `cat /etc/fstab`
> 
>     * did you connect the removable-media plug as mentioned in the [README](https://github.com/nextcloud/nextcloud-snap/blob/master/README.md) in order to grant the snap permission to access external drives.
> 
>     * also show `sudo cat /var/snap/nextcloud/current/nextcloud/config/config.php | grep 'directory'`
> 
> 
> @kyrofa this should be possible theoretically, but I haven't tried mounting an NFS-share as data-directory?

Yeah, sorry, I kinda went on one breath while writing this post.

I have a single VM which holds my NC snap installation. The installation went well and NC was functional.
I also have NFS share from an external host (TrueNAS) which I've attached to that VM. The location is `/mnt/nfs_share`

I can read/write to this mounted NFS share using my root account. The `nfs_share` folder belongs to the root account.

Configurations which I've applied to NC are the following:

`/var/snap/nextcloud/current/nextcloud/config/config.php` edits:
'datadirectory' => '/mnt/nfs_share,`

` $ sudo mv /var/snap/nextcloud/common/nextcloud/data /mnt/nfs_share`

Both NC and the VM itself were restarted after applying those changes. I've added the NFS share via `fstab`, so I'm sure that it will be mounted after system reboot.

**Comment by scotrod** [comment]
Made some progress!

I missed this step:
_did you connect the removable-media plug as mentioned in the [README](https://github.com/nextcloud/nextcloud-snap/blob/master/README.md) in order to grant the snap permission to access external drives._

So now that I have covered this as well, I at least get the NC homescreen, followed by error message:
```
Error
Your data directory is invalid.

Ensure there is a file called ".ocdata" in the root of the data directory.
```
The file `.ocdata` is in the `data` folder with permissions:
```
-rw-r--r-- 1 root root
```

Not sure where I should go from here?

**Comment by scubamuc** [comment]
> I've added the NFS share via fstab, so I'm sure that it will be mounted after system reboot.

great... 
so have you rebooted to confirm?
are you sure you connected the removable-media plug?

if this is C&P, then ther's a typo in `/var/snap/nextcloud/current/nextcloud/config/config.php`
please double check `'datadirectory' => '/mnt/nfs_share,` its not `datadirectory` but `directory` and there shouldn't be a comma there at the end of that line 

judging by @kyrofa's answer:
> Yeah me neither.

this is a first for most of us. so there may be caveats putting your data-directory on an NFS-mount. Maybe we can wait and see if some Nextcloud-snap folks here have had experience...

please show your logs as per  [logging an issue ](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts)

**Comment by scotrod** [comment]
> there's typo's in `/var/snap/nextcloud/current/nextcloud/config/config.php`
> please double check `'datadirectory' => '/mnt/nfs_share,` its not `datadirectory` but `directory` and there shouldn't be a comma there at the end of that line

This is strange... originally, my config originally had `datadirectory`, not just `directory`. Anyways I've changed it. Now I get the same error message, but with just white screen as a background, instead of NC's wallpaper.

Logs provided as a gist, since GitHub won't allow me to paste so much content in a single comment:
https://gist.github.com/scotrod/5dcd1fddc462109dcd4d39758f3ec956

**Comment by scubamuc** [comment]
okay... looks like there're still typos in `/var/snap/nextcloud/current/nextcloud/config/config.php`

I'm not sure what the take is on `.ocdata`but I'm guessing that Nextcloud-snap is expecting the file in the data-directory and is not finding it there because of the typo in `/var/snap/nextcloud/current/nextcloud/config/config.php`.

**Comment by scotrod** [comment]
Thanks, so what should I do next?

What type of typos are still available in the document? I'm confused if I should edit the mentioned one because of snap or keep it vanilla.

**Comment by scubamuc** [comment]
sorry, I messed up there...
``
 // ...
 'datadirectory' => '/mnt/nfs_share',
 // ...
```

**Comment by scotrod** [comment]
Applied those exact changes and I am back at:
```
Error
Your data directory is invalid.

Ensure there is a file called ".ocdata" in the root of the data directory.
```
Now the NC background is visible (if that matters). Should I pull out another set of logs?

**Comment by scubamuc** [comment]
@scotrod lets see if some other folks here can help with the `.ocdate` take. 
maybe @kyrofa can lend an hand

**Comment by kyrofa** [comment]
1. By default, the data directory is `'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',`
2. You ran this command: `sudo mv /var/snap/nextcloud/common/nextcloud/data /mnt/nfs_share`
3. The `nfs_share` directory already existed because you mounted something into it. That implies that you now have a `/mnt/nfs_share/data` directory.
4. As a result, you need `'datadirectory' => '/mnt/nfs_share/data',`

**Comment by scotrod** [comment]
Eureka!

So, because I previously commented exactly what @scubamuc proposed, I was missing the `data` folder inside: `/mnt/nfs_share`

Now I have the complete path in my config file:
```
  'datadirectory' => '/mnt/nfs/data',
```

AND IT WORKS!

I will keep you posted of any further issues... Thank you a lot, both of you folks!

**Comment by scubamuc** [comment]
> So, because I previously commented exactly what @scubamuc proposed, I was missing the data folder inside: /mnt/nfs_share

sorry about that... my bad

**Comment by scotrod** [comment]
Don't be sorry for anything pal! Thanks again! I will test some things, as I understand that there aren't many snap users who have mounted NFS share as a storage like me. If nothing pops up, I will close this one.

**Comment by scubamuc** [comment]
Hey @scotrod, I'll close this then?
