### ISSUE TITLE
Add support to add additional PHP extension by adding an extension folder from the data dir (/var/snap/nextcloud/current/php/extensions)

### ISSUE THREAD

**Issue by ykoehler** [nextcloud-snap/nextcloud-snap#2428]
Ok, sorry, this is more a question than a bug report, I am not an expert in snap, but I was wondering if there was a way to let the end-user adds more php extensions to the php instance used by the snap nextcloud by adding a folder from the /var/snap/nextcloud/current as part of the PHP extension search paths as well as moving the php.ini inside that folder to let the end-user have more control over it.

The structures would be like

```
/var/snap/nextcloud/current/php/
  php.ini
  extensions/
```

End-user would then be able to add extensions to the folder and enable them by altering the php.ini (same for the rest of the php.ini file as well.

This would help people adding extensions they may require from app or developing new things using the snap nextcloud package (or just testing against it a new app, etc).

**Comment by scubamuc** [comment]
no need to be sorry, this is the right place for questions. 
this one is best answered by the devs.
@kyrofa, any thoughts?

**Comment by kyrofa** [comment]
Hey there @ykoehler, thanks for the report. However, while your idea sounds good on paper (it's the kind of approach I wish was possible), it's not actually feasible in reality. That idea only works with an extension that either:

1. Has zero dependencies
2. Is statically linked

Basically, this concept won't work for the vast majority of extensions, and the ones that do work will only work because they fit into a tiny edge case. Such things turn into footguns rather than features.

**Comment by ykoehler** [comment]
Are there instruction then on how to modify and build my own snap based on the work done for this snap so that I can package my app/extension as part of a nextcloud snap I would like to run?

**Comment by ykoehler** [comment]
ha, just saw the section hacking... didn't realize that it was how to rebuild the package lol, will try that way.
