### ISSUE TITLE
Unable to add LDAPS, unable to configure LDAPS certificate

### ISSUE THREAD

**Issue by wawuo** [nextcloud-snap/nextcloud-snap#2488]
#### Describe the bug
A clear and concise description of the bug.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

    $ snap list nextcloud

and:

    $ snap version

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).

**Comment by scubamuc** [comment]
please log an issue with the nextcloud folks...

**Comment by wawuo** [comment]
> please log an issue with the nextcloud folks...

This is not a problem with Nextcloud, but with snap Nextcloud. I can use LDAPS in the traditional Nextcloud, but it is not possible to implement it in Snap Nextcloud.

**Comment by wawuo** [comment]
> please log an issue with the nextcloud folks...

This is not a problem with Nextcloud, but with snap Nextcloud. I can use LDAPS in the traditional Nextcloud, but it is not possible to implement it in Snap Nextcloud.

**Comment by scubamuc** [comment]
the TLS CACERT certificates for LDAPS are located outside of Snap [confinement](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Nextcloud-snap_Snap-confinement).

@kyrofa  do you have any ideas how the snap can handle LDAPS?

**Comment by kyrofa** [comment]
I'm afraid I know absolutely nothing about LDAPS, but if the snap can't read the certs that seems problematic indeed.

**Comment by scubamuc** [comment]
> I'm afraid I know absolutely nothing about LDAPS, but if the snap can't read the certs that seems problematic indeed.

@wawuo this was to be expected.

**Comment by lug-gh** [comment]
I don't understand why this issue was closed; after all, it's definitely a “problem” with the snap and not with Nextcloud itself.

Anyway, here’s my current “solution.”

[Since I also use a custom certificate from the same CA for the Apache Snap component](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Managing-HTTP-encryption-(HTTPS)#custom-certificate-for-nextcloud-snap), the CA is already mounted in the Snap. Therefore, I can edit the Systemd service for php-fpm and set the required environment variable there.

`/etc/systemd/system/snap.nextcloud.php-fpm.service.d/override.conf`
```
[Service]
Environment="LDAPTLS_CACERT=/var/snap/nextcloud/current/certs/custom/chain.pem"
```

Of course, this path may differ for other users, so you'll need to adjust it accordingly.

**Comment by kyrofa** [comment]
@lug-gh because it's not a problem we can solve. The nextcloud snap is confined like every other snap. If you want the snap to read certs, you need to put them in a place it can read from within confinement, as you did.

**Comment by lug-gh** [comment]
@kyrofa 
Thank you very much for your response. I asked the question because I didn’t quite understand why the ticket was closed. I simply didn’t understand where this CA certificate under “/etc/ssl/certs/dmc_certificate.crt” was supposed to come from in the first place. I dug a little deeper, and it turns out this isn’t a requirement from Nextcloud or LDAPS—some user just included it in a sample guide, and apparently everyone else took it as a standard and blindly copied it. (You can find this path in dozens of community posts)

I'm not even sure if @scubamuc's basic claim that snap doesn't have any (read) access to /etc/ssl/certs is correct, because when I put my CA certificate in /etc/ssl/certs/, the snap can access it just fine, see:

```
root@nextcloud:~# LDAPTLS_CACERT=/etc/ssl/certs/chain-forsnap.crt nextcloud.occ ldap:test-config s01
The configuration is valid and the connection could be established!
```
(I also tested it that way with the override file for php-fpm)
I don't know if this is intentional, or if it's just possible because I'm using the “removable-media” extension.

Is the approach I took correct, or will it cause other problems down the road?
Because if that's the right way to do it, then maybe I'd add it to the wiki so other people don't run into the same problem.


One more side note: The `nextcloud.occ` command doesn't seem to recognize the environment variable. Where would be the right place to define it? System-wide on the host, or somewhere specific within the Snap?

```
root@nextcloud:~# nextcloud.occ ldap:test-config s01

In LDAP.php line 367:

  Lost connection to LDAP server.


ldap:test-config <configID>
```
```
root@nextcloud:~# LDAPTLS_CACERT=/var/snap/nextcloud/current/certs/custom/chain.pem nextcloud.occ ldap:test-config s01
The configuration is valid and the connection could be established!
```

**Comment by scubamuc** [comment]
> I asked the question because I didn’t quite understand why the ticket was closed

its certainly no big deal re-opening the issue! remember this is **not a ticket**, this is a request, we're volunteers and certainly no obligation.

at the time (Aug. 2023) the issue was closed as there were more prominent issues and no manpower available for debugging the issue as requested. 

being a non-dev I'm admittedly overzealous at times and try to keep the devs backed so they can do their magic, that is my prorogative right? 

closing the issue has not prevented an interesting discussion though --> and we appreciate that 👍

feel free to create a new issue with reference to this one if you're keen on debugging and documenting this for the wiki. we'll certainly add your suggestion.

> not even sure if [@scubamuc](https://github.com/scubamuc)'s basic claim that snap doesn't have any (read) access to /etc/ssl/certs is correct

hmm... mind telling us which OS you're running the snap on?

>  if that's the right way to do it, then maybe I'd add it to the wiki so other people don't run into the same problem

great idea 🥇 feel free to make a suggestion ✔️

**Comment by lug-gh** [comment]
Okay 👍 

I'm using Ubuntu 24.04,  and I also tested other paths like `/usr/local/share`, thos were not accesible within the snap.

For now, I'm away the next two weeks, but after that I'll dig a little deeper, to find out what's up with this LDAPTLS_CACERT env var and what's the best way to use it, and after that create a pull request for the wiki :)

**Comment by SuperSpital** [comment]
Thank you @lug-gh for your "current" solution. I did it the same way and it works. The only problem is that configuration gets lost after automatic nextcloud updates.

**Comment by lug-gh** [comment]
Hi @SuperSpital, thank you very much for pointing that out. You're absolutely right. However, I'm still pretty much in the dark as to why that's the case. The override file `/etc/systemd/system/snap.nextcloud.php-fpm.service.d/override.conf` still exists, and its content is still
```
[Service]
Environment="LDAPTLS_CACERT=/var/snap/nextcloud/current/certs/custom/chain.pem"
```

It might be worth trying to declare the environment variable in the global `/etc/environment` file, since the PHP-FPM Snap uses this file by default. We'll have to see if it survives an update.
