### ISSUE TITLE
Dav endpoints redirecting incorrectly

### ISSUE THREAD

**Issue by 008kevin** [nextcloud-snap/nextcloud-snap#2686]
#### Describe the bug
Nextcloud says that the webserver is not set to resolve „/.well-known/caldav” and „/.well-known/carddav”. I decided to check it out in a browser, and sure enough, it redirects to `https://nextcloud.example.com:444/remote.php/dav/`. This is wierd because i have redirect url set to be default https, no port is set. Port 444 is used for nextcloud to haproxy, and haproxy on 443 to the internet. Haproxy is using a somewhat modified reccomended config, and is acting as pass through. From the screenshot attached i can see that the response has `Server: Apache`, so i believe that the request is reaching nextcloud snaps apache instance and that is causing the issue

#### To Reproduce
1. Install nextcloud snap as recomended using the docs
2. Try to follow the dav pages

#### Expected behavior
They should redirect to default https port 443 as set, not 444

#### Screenshots
![kép](https://github.com/nextcloud-snap/nextcloud-snap/assets/77583631/fe55c7d1-17d0-4a30-a070-9ae56268e1d4)

#### OS/snapd/snap version
OS: Ubuntu 22.04

```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  27.1.6snap1  40228  latest/stable  nextcloud✓  -
```

```
$ snap version
snap    2.61.1
snapd   2.61.1
series  16
ubuntu  22.04
kernel  6.5.0-18-generic
```

#### Logs
[logs.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/14320560/logs.txt)

_Note: Redacted my domain since its a home server and i have a static ip, can send in private for testing if needed just dont want it to be publicaly available if thats fine_
Thanks for the help, and let me know if any further info is needed!

**Comment by scubamuc** [comment]
Welcome @008kevin and thanks for your request

> Haproxy is using a somewhat modified reccomended config, and is acting as pass through

maybe following Link helps https://stackoverflow.com/questions/71171414/haproxy-breaks-dav-well-known-redirects-in-nextcloud

@Pilzinsel64 could you assist please?

**Comment by 008kevin** [comment]
Hey, thanks for the quick response
I was thinking to hand off ssl to haproxy and do the redirecting there, but just wanted to report this since i couldnt find any isue about it with a quick search (apearantly not a good enaugh searcher). If im aware, the apache config is read only in the snap, would there be a way to have those port settings be available for apache as well somehow?
When i get my config i can add a PR to add it to the config on the guide with steps for ssl if needed to help out.

**Comment by scubamuc** [comment]
@008kevin, yeah the apache config is read only. feel free to make a PR.

please close here when you're happy

**Comment by scubamuc** [comment]
@008kevin, i've tried to understand what you're trying to do. not being familiar with haproxy i'd like to point you to config using [NPM](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager). I am aware that NPM is handling termination in this example and you're wanting to pass through the reverse proxy which is explained [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy).

its not clear though if your setup is configured to port444 or not. if so, why if you're wanting to pass through anyway? 

also have you set `overwritehost` or `overwriteprotocol` because surely the snap would not redirect to port444 if it hasn't been told to?

possibly @kyrofa could assist since he has haproxy setup
