### ISSUE TITLE
Unable to play .mkv video files properly

### ISSUE THREAD

**Issue by liuxyon** [nextcloud-snap/nextcloud-snap#2699]
I just installed the latest version nextcloud on Ubuntu 23.10 system，it unable to play .mkv video files properly.
The video image is displayed during playback, but there is no sound. And the video speed is abnormal.How should I solve this?

**Comment by scubamuc** [comment]
@liuxyon welcome and thank you for your request.

assuming you have your Nextcloud snap installed on a server and are accessing the files from a client with Ubuntu 23.10 installed. the client upon which you are trying to view matroska video files does not have the necessary CODECS installed to play .mkv video files. this would be a client issue and is certainly not an Nextcloud snap issue.

**Comment by scubamuc** [comment]
@liuxyon thank you for your feedback.

so I've gone ahead and tested this. indeed matroska video files are not displayed.
this is a third party issue so surely there is nothing we can do in the snap. See [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)
