### ISSUE TITLE
File upload - Toastify is Awesome - notice on file uploading of size > 1 mb

### ISSUE THREAD

**Issue by aquananu** [nextcloud-snap/nextcloud-snap#2717]
Running Snap nextcloud on Ubuntu 22.04.4 LTS
core 5.15.0-101-generic 
Nextcloud Version
 27.1.8

Since a couple of days, on uploading a file to deck or a folder is giveing the error toast messsage - toastify is awesome

There have been no changes in the system, except the system has been updated using the apt-get update && apt-get upgrade command

This was working fine earlier.

Can someone help me resolve this.

**Comment by scubamuc** [comment]
Hi @aquananu, assuming this "Toastify" thing is a third party app? See [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)

See this on their [GitHub](https://aleab.github.io/toastify/):

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/19ab693b-db07-4230-8d1e-9415a189c211)

This is certainly not a Nextcloud snap issue

**Comment by scubamuc** [comment]
@aquananu, so I've tested this in Deck:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/88b9895d-b8ef-4455-b609-7e432299b28b)

without issues here.

I'm afraid you'll have to describe your steps in more detail... maybe you can post a screenshot? please make sure this is not a third party issue.

**Comment by aquananu** [comment]
Hi, everyone

The problem lies in the reverse proxy that was being used, same has been reconfigures and it omitted the upload limits

So if you are running NGINX kindly refer to the link https://www.tecmint.com/limit-file-upload-size-in-nginx/ to specify the file size that can be uploaded.

Hope this will be helpful for anyone who encounters this issue ever.
