### ISSUE TITLE
PHP Vulnerability - CVE-2024-2961

### ISSUE THREAD

**Issue by Gabgobie** [nextcloud-snap/nextcloud-snap#2722]
Sources:
https://nvd.nist.gov/vuln/detail/CVE-2024-2961
https://youtu.be/kQdRT2odUIk?si=QJ9UEjePnVfSm0UI

TL;DR: Is nextcloud-snap safe to use or when is a patch ready? What should we do in the mean time? Take the instance offline?

L;R:
Disclaimer: I am by no means an expert but just worried about the safety of my Nextcloud instance.

From what I am understanding, this is a bug in the compiler which leads to a major exploit in php. Nextcloud is using PHP. Is the snap distribution of Nextcloud already using a PHP version that has been compiled with the patched compiler? If Nextcloud is currently affected, when is a patch to be expected and what should we do until then?

**Comment by scubamuc** [comment]
@kyrofa, just to be sure, 
could snap users be effected considering snap confinement?

**Comment by kyrofa** [comment]
After a quick glance, looks like it's not the compiler, but libc itself. The snap is currently built against Ubuntu Bionic, which is [still awaiting triage](https://ubuntu.com/security/CVE-2024-2961) which means it could indeed be vulnerable. Yes, confinement is still in place, and Ubuntu has assigned this a Medium, so I wouldn't be too worried about it. We'll get the fix when they fix the Bionic libc.

**Comment by pachulo** [comment]
The PHP folks published [an statement](https://www.php.net/archive/2024.php#2024-04-24-1).

> Or we can update to core20.

But we should re-write the local snapcraft plugins as V2 plugins for that, and the sad thing is that they would only be valid for core20, [as there is no such capability in neither core22 or core24](https://forum.snapcraft.io/t/local-v2-plugin-base-core22/32227/2?u=pachulo).

**Comment by pachulo** [comment]
A little update: it seems that [the fix was already released for bionic](https://ubuntu.com/security/CVE-2024-2961) as an Ubuntu Pro/[Expanded Security Maintenance](https://ubuntu.com/security/esm?ref=itsfoss.com) update.

As I understand from [here](https://snapcraft.io/docs/snapcraft-esm#heading--launchpad), by building the snap on Launchpad we are covered, aren't we @kyrofa ?

**Comment by kyrofa** [comment]
> ... by building the snap on Launchpad we are covered

Technically no. Not because you're wrong, to be clear, but because we don't include libc in the nextcloud snap, so it doesn't matter where we build. libc is part of the core18 snap. Looks like the latest amd64 rev is 2823, and you can see what's in there:

```
$ grep libc6 /snap/core18/2823/snap/manifest.yaml
    - libc6-dev=2.27-3ubuntu1.6+esm1
    - libc6=2.27-3ubuntu1.6+esm1
```

It doesn't look like v2.27-3ubuntu1.6+esm2 is in there yet, but it does indeed include ESM stuff, so I don't think we need to sweat this. It'll probably be contained in the next release they spin.
