### ISSUE TITLE
Support for allow only localhost 

### ISSUE THREAD

**Issue by r00t9** [nextcloud-snap/nextcloud-snap#2747]
Can we have the option to allow only for localhost:8080, when I have port 80 and nginx I need to create iptables for this.

**Comment by scubamuc** [comment]
@r00t9 welcome and thanks for your request.

it is unclear what you are trying to do. please be more specific and describe your setup in more detail. you definitely want to acquire an SSL certificate, because Nextcloud will be almost unusable without HTTPS encryption! 

>The only thing we recommend you do up front is enable HTTPS. Nextcloud snap includes a service for automated HTTPS encryption using Lets Encrypt, or self-signed certificates. 

TCP ports 80 and 443 are quite the commodity: you only have one of each! supposing you have nginx web server on port 80 and nginx is not configured as reverse proxy, you may want to change the nextcloud snap port to port 81. see [port configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Port-configuration). alternatively you could change the nginx port to port 81 leaving port 80 for nextcloud snap.

if you need certificates for port 80 or 81 you will need to [configure reverse proxy](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) and [NGINX proxy manager reverse proxy with termination](https://github.com/nextcloud-snap/nextcloud-snap/wiki/NGINX-proxy-manager).

**Comment by ttencate** [comment]
I think my use case is similar, so I'll just hijack this issue and provide the requested information.

I have NextCloud, installed through snap, sitting behind an nginx reverse proxy. Nginx is terminating the SSL connection to `nextcloud.example.com` and proxying this, unencrypted, to NextCloud, which listens on port 8085. I'm managing the certificates in nginx through certbot. The machine is also hosting several other websites, so I can't have NextCloud have port 80 and 443 all to itself.

However, NextCloud insists in opening up port 8085 to the entire world, hosting my NextCloud instance in plain http (I'm not even sure if it works). I have to block that using a firewall rule. So what I would need is a way to tell the snap to only listen on localhost (127.0.0.1 and/or ::1), instead of 0.0.0.0. Hopefully this is not too hard to add.

**Comment by scubamuc** [comment]
@ttencate, 
>I think my use case is similar, so I'll just hijack this issue and provide the requested information.

this is not a similar or the same issue, since NGINX is terminating TLS... but never mind, we'll try to help anyway.

you could change the Nextcloud snap port so that 80 is not required; see [HTTP/HTTPS port configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Port-configuration) that way you can basically use any port combination.... as long as the reverse proxy is forwarding correctly and handles SSL encryption.

**Comment by ttencate** [comment]
> this is not a similar or the same issue, since NGINX is terminating TLS...

The original issue report didn't specify whether or not nginx was terminating TLS. But never mind.

> you could change the Nextcloud snap port so that 80 is not required

Yes, I'm already doing that. As I mentioned, I changed it to port 8085.

But NextCloud will still listen on port 8085 _globally_, and accept connections on port 8085 from anywhere:

```
$ sudo netstat -lpn | grep 8085
tcp6       0      0 :::8085                 :::*                    LISTEN      2800/httpd          
```

Notice the `:::8085`, i.e. it listens on `::`. For another service that I'm running, which _can_ be properly configured, this says `::1:8085`, i.e. it listens only on `::1`.

The intent is, of course, that all connections go through nginx first. That's why NextCloud needs to listen on the local loopback interface only.

**Comment by scubamuc** [comment]
@ttencate 
> as long as the reverse proxy is forwarding correctly and handles SSL encryption.

sounds like a reverse proxy issue to me... 

@nextcloud-snap/developers could you assist please?

**Comment by ttencate** [comment]
The reverse proxy is working perfectly, and has nothing to do with this. I can access NextCloud through `https://nextcloud.example.com` just fine.

The only issue is that NextCloud is _also_ accessible through `some-completely-other-domain.example.com:8085`, and the snap provides no way to lock this down.

**Comment by kyrofa** [comment]
@ttencate is correct, it would be ideal if the snap wasn't listening on the external interface in such situations. It hasn't been the highest priority to add in the past because this use-case isn't the most common, and locking down unused ports with a firewall is standard practice anyway.
