### ISSUE TITLE
Hub 8 Assistant 2.0 App missing

### ISSUE THREAD

**Issue by and-2000** [nextcloud-snap/nextcloud-snap#2792]
I got the update to Nextcloud 29 today. I can't find Assistant 2.0 under the apps. 

I use Ubuntu 22.04.

Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  29.0.2snap1  42890  latest/stable  nextcloud✓  -

snap    2.63+22.04
snapd   2.63+22.04
series  16
ubuntu  22.04
kernel  5.15.0-112-generic

**Comment by scubamuc** [comment]
@and-2000 welcome and thanks for your request.

AI in Nextcloud snap is not working yet... we are looking into this. Generally these apps are considered third-party-apps and cannot be supported by the Nextcloud snap Team, so you'd be better off creating an issue with the app developers. 

see also [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)

**Comment by and-2000** [comment]
Thanks for the answer. I thought assistant 2.0 is a part of Nextcloud 29 / Hub 8. And the way to activate this feature is the App.
Or is there another way?
Thank you for your help!

**Comment by scubamuc** [comment]
@and-2000 
> I thought assistant 2.0 is a part of Nextcloud 29 / Hub 8. And the way to activate this feature is the App.

this is correct... see [here](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-why-is-nextcloud-snap-version-out-of-sync-with-upstream-nextcloud)

Nextcloud snap is designed to be easy to install and simple to maintain. The ideal Nextcloud snap is an "install and forget" Nextcloud service that works on most architectures and updates itself without needing administrative skills. Combining Nextcloud with snapd makes it a perfect fit for IoT or scalable environments. Snapd is a secure and robust technology which the Nextcloud snap team has embraced.

The Nextcloud snap team packages a finished stable upstream Nextcloud, **adds some snap magic**, tests and releases that snap package. _Since none of the Nextcloud snap team are upstream Nextcloud developers_, they need to ensure that the Nextcloud snap does what it should. That entails packaging and testing fresh installs as well as automated upgrades and updates so that the Nextcloud snap community has peace of mind.

Sometimes the Nextcloud snap team needs to wait for some Nextcloud issues to be resolved upstream before releasing a stable working Nextcloud snap to the public. Some upstream changes **may need more snap magic** to ensure that it simply works, which requires careful configuration and testing.

> Or is there another way?

we're working on it

**Comment by and-2000** [comment]
Thank you very much!
So i will wait.

**Comment by scubamuc** [comment]
@and-2000 

so I've checked on this... can you confirm your search for that assistant app. My search for "assist" finds the app:

![grafik](https://github.com/nextcloud-snap/nextcloud-snap/assets/54933878/9c495157-3182-4bd4-b5b5-67dde508a019)

but **please don't install that app** it will not work yet!

I'd like to close this issue nonetheless, so please confirm if you agree.

**Comment by and-2000** [comment]
Yes: Nextcloud Assistant is the app.
Of course it's ok for me to close the issue.
Thanks for your help!

22.06.2024 16:06:01 scubamuc ***@***.***>:
