### ISSUE TITLE
Nextcloud 30

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud-snap/nextcloud-snap#2898]
### Pending todos
- [x] Wait for 30.0.1 stable
- [x] Create branch [`29`](https://github.com/nextcloud-snap/nextcloud-snap/tree/29)
- [x] Create label [`29`](https://github.com/nextcloud-snap/nextcloud-snap/labels/29)

### Pending PRs
- [x] https://github.com/nextcloud-snap/nextcloud-snap/pull/2927
- [x] Release new snap

### Pending upstream issues
_None_

**Comment by pachulo** [comment]
This is now on the `latest/candidate` channel for everyone to test @nextcloud-snap/developers

**Comment by scubamuc** [comment]
@pachulo, needs testing?

**Comment by pachulo** [comment]
@scubamuc yes, please!
Thanks!

**Comment by scubamuc** [comment]
fresh install tests completed without issues

1. `sudo snap install nextcloud --channel=latest/candidate`
2. setup and install recommended
3. `enable-testing.sh && enable-office.sh &&  sudo snap restart nextcloud`

![grafik](https://github.com/user-attachments/assets/4e2defa3-1a20-4ef6-8d06-916f3dd9b5db)

![grafik](https://github.com/user-attachments/assets/98995a6e-f8f4-4ece-9a2b-a108856e078a)

![grafik](https://github.com/user-attachments/assets/b732bdfd-504e-470f-b2a1-c7ec655940c5)

logs look fine

**Comment by pachulo** [comment]
It would be great if you can upgrade as much production instances as possible.

**Comment by scubamuc** [comment]
@pachulo 
>  great if you can upgrade as much production instances 

sorry, that's out of the question. production stays on stable until final 🤔
the only way to test this would be to clone the lxc's? that will take a while... and i'm not up to it.

**Comment by scubamuc** [comment]
test upgrade from 29.0.8snap1
`sudo snap refresh nextcloud --channel=latest/candidate`

![grafik](https://github.com/user-attachments/assets/795980c5-9511-484a-ae8b-fa22cc229e8d)

![grafik](https://github.com/user-attachments/assets/51bca918-8fd9-46a6-a3eb-2904ff1c20ae)

![grafik](https://github.com/user-attachments/assets/646d30b3-eb67-47ce-9a24-68b22baaa08b)

![grafik](https://github.com/user-attachments/assets/1d61f974-4abf-4036-82a5-5d93acc8d045)

error in log... third party?

**Comment by scubamuc** [comment]
app seems to work though:

![grafik](https://github.com/user-attachments/assets/30ac3802-bc8f-41ac-a987-c888f24f9f81)

i'll look at this later and see if something is missing!

**Comment by Pilzinsel64** [comment]
MY private prod runs pretty well and the upgrade went fine. No changes since my last report.

**Comment by scubamuc** [comment]
@pachulo, so I've successfully upgraded my personal prod. (cloned) instance 
![grafik](https://github.com/user-attachments/assets/54b79a2b-5045-4abd-87da-2245af1c40a4)

![grafik](https://github.com/user-attachments/assets/7ae5e90c-46b7-4d63-a0c0-9a7f8a4cfa61)

![grafik](https://github.com/user-attachments/assets/c99150fe-1930-4278-8d2e-e330e48a418d)

here's my log... 

![grafik](https://github.com/user-attachments/assets/6941c638-3723-4f6e-acea-b84dfa0ecd4e)

- the spreed error is reproducible see above! but talk app works fine. this looks like the spreed is "incompatible".

- the richdocuments error is reproducible... might be connected to #2919 -- office works fine though, so the error is not fatal.

- the maps app throws an exception because its not compatible with NC30 yet 

- other log entries are old entries...

**Comment by scubamuc** [comment]
@nextcloud-snap/developers 
...this looks good to me, as soon as those apps (@Pilzinsel64 please confirm) have been updated we should be ready to go?

**Comment by user8446** [comment]
Hi just adding that after stopping nextcloud and doing a snapshot I tried to upgrade my production instance but it hung on `Run pre-refresh hook of "nextcloud" snap if present` . Nextcloud was still stopped and not running.

After aborting and starting nextcloud and then running the upgrade again it upgraded without issue. Apparently it has to be running to upgrade?

As for nextcloud itself there are no errors in the log, setup checks is fine, and everything runs and works successfully.

**Comment by scubamuc** [comment]
@user8446 thanks for you tests... that's very appreciated 👌

> apparently it has to be running to upgrade?

yeah, correct! the snap needs to be in a running state in order to upgrade. probably due to the snapshots that need to be made...  maybe one of the devs can explain`?

> As for nextcloud itself there are no errors in the log, setup checks is fine, and everything runs and works successfully.

don't forget to revert or return to `stable` once 30.0.1snap1 is released...

----

as a side note, i've recently upgraded the os on all my (9) servers. during my tests i stopped snaps, dockers and containers before doing the os upgrade which led to some failed upgrades where the snaps, dockers and containers wouldn't restart for some reason... whereas leaving the containers and snaps in a running state lead to successful os upgrade in every test scenario.

**Comment by pachulo** [comment]
This has been released to `latest/stable`
Thanks for all the testing and feedback!
