### ISSUE TITLE
[Reconize] bin/node file exist, can't be executed 

### ISSUE THREAD

**Issue by cm-t** [nextcloud-snap/nextcloud-snap#2944]
#### Describe the bug

It seems the app `reconize` is well installed, but is unable to execute node.

#### To Reproduce
1. As Admin of my nextcloud instance i go to `/index.php/settings/admin/recognize`
3. In the Node.js fieldset, I update the path according to the message telling me that snap install must use:
    * `/var/snap/nextcloud/current/nextcloud/extra-apps/recognize/bin/node`  
4. F5 the page after setting is saved
5. See error: `Impossible de lancer l'exécutable Node.js. Il peut être nécessaire de configurer manuellement le chemin vers un exécutable fonctionnel.`  (_can't launch node_)

1. Log into (ssh) my snap server
2. `ls`  the file with success
3.  launch the file fail

#### Expected behavior
No error / the binary should execute

#### Screenshots

![image](https://github.com/user-attachments/assets/03f055ad-7e0e-4eb9-983f-a3b031c3848f)

For the records, `occ recognize:download-models`  was done sucessfully: 

![image](https://github.com/user-attachments/assets/d076e826-16a8-4ced-a5e3-8bbf42e2d2cd)

#### OS/snapd/snap version

``` bash
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  30.0.1snap1  44812  latest/stable  nextcloud✓  -
``` 

   
``` bash
$ snap version
snap    2.63
snapd   2.63
series  16
kernel  4.15.0-230-generic
``` 

#### Logs

``` bash
~$ sudo ls -alh /var/snap/nextcloud/current/nextcloud/extra-apps/recognize/bin/node
-rwxr-xr-x 1 root root 95M Oct 24  2023 /var/snap/nextcloud/current/nextcloud/extra-apps/recognize/bin/node

~$ sudo /var/snap/nextcloud/current/nextcloud/extra-apps/recognize/bin/node --version
sudo: unable to execute /var/snap/nextcloud/current/nextcloud/extra-apps/recognize/bin/node: No such file or directory
``` 

```bash
~$ sudo nextcloud.occ recognize:classify
Processing storage 2 with root ID x
No files left to classify
No files left to classify
face classifier end
No files left to classify
No files left to classify
Processing storage 3 with root ID xx
No files left to classify
No files left to classify
face classifier end
No files left to classify
No files left to classify
Processing storage 5 with root ID xxx
No files left to classify
No files left to classify
face classifier end
No files left to classify
No files left to classify
Processing storage 7 with root ID xxxx
No files left to classify
No files left to classify
face classifier end
No files left to classify
No files left to classify
Processing storage 10 with root ID xxxxx
No files left to classify
No files left to classify
face classifier end
No files left to classify
No files left to classify
```

**Comment by scubamuc** [comment]
@cm-t 
> It seems the app reconize is well installed, but is unable to execute node.

see [FAQ's](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's) this third party app is [incompatible](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#known-incompatible-third-party-apps) due to [confinement](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-what-is-snap-confinement)

**Comment by pachulo** [comment]
This is a [know issue](https://github.com/nextcloud-snap/nextcloud-snap/issues/2808), but I'm afraid we still don't have an ETA for [the solution](https://github.com/nextcloud-snap/nextcloud-snap/issues/2908).

**Comment by htot** [comment]
If nextcloud-snap would include a working nodejs, Recognize would be able to fall back to that one.
The alternative, Recognize providing the right one seems to be blocked (already 2 years?) due to the glib issue as @pachulo says.

For this reason there are recommendations (including from Gemini) directing people to a docker version (AIO) of Nextcloud. This is a pity, because this snap version works very well.

Even if you don't want to add node by default, shouldn't there be a way to install tools that are required by an app?
