### ISSUE TITLE
CPU usage become abnormally high

### ISSUE THREAD

**Issue by tianen1108** [nextcloud-snap/nextcloud-snap#2947]
#### Describe the bug
After I updated my server by "apt update & apt upgrade", I found that the server CPU usage become 99% for long time.
snap.nextcloud.php-fpm.service takes 60%, snap.onlyoffice-ds.documentserver.service takes 20%.
Before the update, my CPU usage is usually kept under 30% in average in normal use.

And another thing I do not know if it is relevant, my colleague reported that the situation lasted 1 week that his PC synced very slowly. He says he have updated the client to newest already.

#### To Reproduce
1. open terminal, input "sudo apt update", then "sudo apt upgrade"
2. reboot
3. open cockpit webpage, find error

#### Expected behavior
CPU usage shall be below 40% usage, and syncing won't take so much time

#### Screenshots
![CPU usage](https://github.com/user-attachments/assets/19dd26ee-2b5a-4b47-b181-e659855ecf1a)
![When it started](https://github.com/user-attachments/assets/fce70425-0634-4773-9506-a80b8aae74bc)

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands:

xxx@xxx:~$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  30.0.1snap1  44812  latest/stable  nextcloud✓  -

and:

xxx@xxx:~$ snap version
snap    2.65.3+22.04
snapd   2.65.3+22.04
series  16
ubuntu  22.04
kernel  6.8.0-48-generic

#### Logs
Please paste in the output from
[this script](https://github.com/nextcloud/nextcloud-snap/wiki/Issue-Debugging-Scripts)
to assist in debugging (note that it's pre-formatted).
[script_output.log](https://github.com/user-attachments/files/17615114/script_output.log)

**Comment by scubamuc** [comment]
@tianen1108 welcome and thanks for your request

you may want to try [database‐apps‐files‐maintenance](https://github.com/nextcloud-snap/nextcloud-snap/wiki/database%E2%80%90apps%E2%80%90files%E2%80%90maintenance)

see also [third party apps](https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-snap-is-not-working-because-of-third-party-app-incompatibility-what-can-i-do)

and issue #2938

**Comment by scubamuc** [comment]
@tianen1108 

this is repetitive:

```
1657:M 04 Nov 2024 04:17:07.023 * 10 changes in 300 seconds. Saving...
1657:M 04 Nov 2024 04:17:07.023 * Background saving started by pid 56138
56138:C 04 Nov 2024 04:17:07.040 * DB saved on disk
56138:C 04 Nov 2024 04:17:07.040 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 M
```
not sure what causes it though... something needs to be saved and its trying over and over taking 300 seconds each time

also you're getting those typical `guzzlehttp` log errors from `richdocuments` which could be because of misconfiguration of Nextcloud Office... 
```
        },
        "richdocuments": {
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "installed_version": "8.5.2",
            "types": "prevent_group_restriction",
            "wopi_url": "http:\/\/192.168.0.100\/extra-apps\/richdocumentscode\/proxy.php?req="
```
see [CODE & Nextcloud Office configuration](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap). 

you have an onlyoffice-documentserver running... is that connection working? why have two office apps enabled? 
```
        "onlyoffice": {
            "DocumentServerInternalUrl": "",
            "DocumentServerUrl": "http:\/\/192.168.0.100:8080\/",
            "StorageUrl": "",
            "advanced": "true",
            "customizationChat": "true",
            "customizationCompactHeader": "true",
            "customizationFeedback": "true",
            "customizationForcesave": "false",
            "customizationHelp": "true",
            "customizationReviewDisplay": "original",
            "customizationTheme": "theme-classic-light",
            "customizationToolbarNoTabs": "true",
            "defFormats": "{\"csv\":\"false\",\"doc\":\"false\",\"docm\":\"false\",\"docx\":\"true\",\"docxf\":\"true\",\"oform\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"otp\":\"false\",\"ots\":\"false\",\"ott\":\"false\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"false\",\"ppsm\":\"false\",\"ppsx\":\"false\",\"ppt\":\"false\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"false\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",
            "demo": "{\"available\":false,\"enabled\":false,\"start\":{\"date\":\"2023-10-16 10:25:05.145726\",\"timezone_type\":3,\"timezone\":\"UTC\"}}",
            "editFormats": "{\"csv\":\"true\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"rtf\":\"false\",\"txt\":\"true\"}",
            "enabled": "no",
            "groups": "[]",
            "installed_version": "9.5.0",
            "jwt_header": "",
            "jwt_secret": "***REMOVED SENSITIVE VALUE***",
            "preview": "true",
            "sameTab": "true",
            "settings_error": "Client error: `GET http:\/\/192.168.0.100:8080\/healthcheck` resulted in a `404 Not Found` response:\nNot found\n",
            "types": "prevent_group_restriction",
            "verify_peer_off": "true",
            "versionHistory": "true"
```

there are some known issues with `fulltextsearch` app, which could also slow things down and cause excessive CPU load
```
        "fulltextsearch_elasticsearch": {
            "enabled": "yes",
            "installed_version": "30.0.0",
            "types": "
```

i'm guessing this is a third party issue... both Nextcloud Office and ONLYOFFICE are calling the same IP `192.168.0.100` which is your localhost and none of these are encrypted. use ONLYOFFICE or Nextcloud office and configure one of those apps correctly.

@nextcloud-snap/developers could you please assist?

----

also consider enabling [http compression](https://github.com/nextcloud-snap/nextcloud-snap/wiki/configure-Nextcloud-snap#http-compression-configuration) which could speed up things on the client side, but has nothing to do with the issue at hand

**Comment by tianen1108** [comment]
@scubamuc Thanks a lot for the reply!

About Office, it's weird, because I disabled OnlyOffice plugin plus stopped OnlyOffice docker container long ago, and I see it still keeps disabled now in the Nextcloud web interface.

Anyways, without any change, today afternoon I found that the CPU load becomes under 30%. Don't know what causes this problem actually. If it happens again I will try going through your points and let you know what the problem is.
