### ISSUE TITLE
How to get httpd listening to 127.0.0.1 instead of 0.0.0.0?

### ISSUE THREAD

**Issue by Magicloud** [nextcloud-snap/nextcloud-snap#331]
Hi, for some reason, I have to set redirection from 0.0.0.0:443 to 127.0.0.1:443, which means nextcloud-snap could not use 0.0.0.0:443 but 127.0.0.1:443. How should I do it? I saw only port settings mentioned here.

**Comment by andschwa** [comment]
I need to do this to, but can't find how. I have other services running on the VM, and I have a dedicated IP for Nextcloud, but it's binding to 0.0.0.0 😦

**Comment by Magicloud** [comment]
@andschwa solution for me, for now, is cloning the source and build the snap myself.

**Comment by andschwa** [comment]
Haha, yeah but that's just a work-around. I feel like this needs to be configurable so the snap is more usable. I didn't _want_ to build it in order to use it easily.

**Comment by kyrofa** [comment]
Assuming #349 seems to work okay, we can build on top of it pretty easily for this feature.

**Comment by andschwa** [comment]
#349 looked awesome (and like quite a bit of work).

My scenario is that I want to host my Nginx HTTPS secured websites on the same server that has the Nextcloud snap installed. Assuming I have a separate IP address on the machine for each website and Nextcloud, I should be able to configure Nginx manually to listen on the necessary IPs (instead of all), and make this snap configurable like #349 but for the IP address for the Apache VirtualHost.

If my understanding is correct, this should all work, and even let me use the Let's Encrypt certbot externally to get certificates for my other websites (though certbot probably listens on all interfaces... not sure what issues I might run into there).

Can you think of any "gotchas" I might have missed in this scenario?

**Comment by kyrofa** [comment]
Sorry @andschwa I missed that question! No, that sounds pretty accurate. The configuration stuff has all landed if this is something you'd like to investigate. Otherwise I'll get to it once I have time.

**Comment by bithex** [comment]
I have a working code that allows the user to change the listening IPv4 address (the Listen directive within httpd.conf and ssl.conf) through a configuration hook with command like "snap set nextcloud listen-address=127.0.0.1".

However I cannot get the snap to listen on IPv6 addresses (except for the loopback on "::1"), not even through hard coding a Listen directive into httpd.conf. Looks to me the apache service is somehow configured to not enable IPv6. Is that correct? - If that is the case, I will submit a pull request with an IPv4 only code, let you guys figure out the IPv6 support deep down and then commit a fully functional IPv4+IPv6 code. That ok?

**Comment by bithex** [comment]
Also, initially, I wanted to do the IP validation on the user's entered listen address against valid configured IPs on the system, e.g. by use of "ip -4 addr" and "ip -6 addr". Turns out snap/snapd has no access to commands in /sbin, so commands like ip, ifconfig and many many others are not accessible to the snap. 
Guess this is a limitation in snapcraft by design?

**Comment by asmaack** [comment]
I see my push request still hasn't been merged, hmm.
Eventually my shop stopped using the snap and we went for the Nextcloud docker instead. 
Personally I recommend that for your senario as you have full freedom to implement listening addresses and ports on systems behind reverse proxies, all through the docker configs.

**Comment by kyrofa** [comment]
Yes, the PR still needs tests, and I haven't had time to add them. If anyone wants to take a crack at that, go for it.

**Comment by yvolchkov** [comment]
Do I understand correctly, that there is no official way to change the bind address, only the port?

**Comment by kyrofa** [comment]
That's correct. Generally only a single interface is exposed anyway so this isn't a high priority for me. If you'd like to resurrect the above PR and add the required tests I'd be happy to review.

**Comment by LeonardoMantovani** [comment]
> I have a working code that allows the user to change the listening IPv4 address

Since I'm running Nextcloud Snap on my server and I was looking exactly for this feature (I don't need ipv6), is this available now?

**Comment by kyrofa** [comment]
No, that PR never got mature enough, feel free to take a crack at it.

**Comment by LeonardoMantovani** [comment]
Sadly, I have zero experience with snaps configuration files, so I don't think I could help :(
Still ready to test it when it will be ready though

**Comment by ttencate** [comment]
I would also like this feature. Meanwhile I found [this workaround](https://github.com/nextcloud/nextcloud-snap/issues/134#issuecomment-575904440): listen on all interfaces, and use the `ufw` firewall to block traffic from the outside world to that port.
