### ISSUE TITLE
Move data location to external drive .ocdata error

### ISSUE THREAD

**Issue by nathan99218** [nextcloud-snap/nextcloud-snap#400]
Hello I have been trying to research this all day and I keep getting the same error "your data directory is invalid Ensure there is a file called ".ocdata" in the root of the data directory. 

Thanks!

**Comment by kyrofa** [comment]
Explain to me exactly what you're trying to do. You had the snap working without any external drive, and now you want to migrate all that date to the external drive?

**Comment by nathan99218** [comment]
sorry if it sounded confusing. What I want to do is to be able to default all of my Nextcloud files on to an external drive instead of the internal drive on my Ubuntu machine. This previous ticket helped a lot but its still not working for me https://github.com/nextcloud/nextcloud-snap/issues/150#issuecomment-267641192. I have moved and changed the data directory to the /media/externaldrive  and then I get this error. "your data directory is invalid ensure there is a file called ".ocdata" in the root of the data directory."
Thanks and sorry I'm new to this stuff.

**Comment by kyrofa** [comment]
Okay much more clear, thank you :) .

Can I see the output of `ls -ld /media/externaldrive`, please?

**Comment by nathan99218** [comment]
The data file is in the right place so I checked the data folder and the drive for the data file i got  ls: cannot access '/media/woodriver/2godd/data' : permission denied and for the external drive I got drwx------ 4 root root 4096 dec 20 14:41
![nextcloud](https://user-images.githubusercontent.com/34723891/34310767-01f96528-e71f-11e7-93ec-e5e94fb3fcc6.jpg)

**Comment by kyrofa** [comment]
Alright, use `sudo` in front of those commands to ensure you don't get permission denied. I'd like to see that as well.

**Comment by nathan99218** [comment]
I should have known to do that sorry. for the data folder I got -rw-r--r--r 1 root root 0 Dec 20 11:21 /media/woodriver/2godd/data
![img_0942](https://user-images.githubusercontent.com/34723891/34310981-28c3efba-e720-11e7-9826-1c53a0fbd058.JPG)

**Comment by kyrofa** [comment]
Alright, one more level: `sudo ls -la /media/woodriver/2godd/data` let's see if that file is in there...

**Comment by nathan99218** [comment]
Weird the .ocdata is in there.
![img_0943](https://user-images.githubusercontent.com/34723891/34311118-36e21a58-e721-11e7-8bec-52c646eeef13.JPG)

**Comment by kyrofa** [comment]
Wait... that's showing 2godd1 as owned by woodriver. But an earlier snippet showed that directory was owned by root. What gives?

**Comment by kyrofa** [comment]
You're switching things around... 2godd, 2godd1...

**Comment by nathan99218** [comment]
Sorry I did notice that too. I do have the data directory set as the 2godd1. I'm not sure why my external drive is showing up with 3 different names. I formatted it before I started using it.
![img_0945](https://user-images.githubusercontent.com/34723891/34312097-37313042-e727-11e7-8d9a-3572cda3aa28.JPG)

![img_0944](https://user-images.githubusercontent.com/34723891/34311997-8e7d3d7e-e726-11e7-8de5-da8d737eaf1b.JPG)

**Comment by yatzy** [comment]
I'm facing similar issue after following directions here:
https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

Steps taken (as root):
    - mounted new external hd as `/mnt/external`
    - changed datadirectory in `/var/snap/nextcloud/current/nextcloud/config/autoconfig.php`
    - ran `snap disable nextcloud`
    - went to look at `/mnt/external`, saw a couple of files, if I remember correctly, one of which was .ocdata
    - didn't bother with it and went on 
    - continued to the end of the instructions

Could it be that `snap disable nextcloud` should be run before changing the datadirectory in config.php?

**Comment by yatzy** [comment]
Ok I ran `touch .ocdata` and when signing to web ui through lan ip I was greeted with this

`Access through untrusted domain

Please contact your administrator. If you are an administrator, edit the "trusted_domains" setting in config/config.php like the example in config.sample.php.

Further information how to configure this can be found in the documentation.`

From wan the site could not be found.

`nextcloud.occ config:system:get trusted_domains` returns right domains...

**Comment by yatzy** [comment]
Ok now after a moment access though domain works fine, from local ip I still get "Access through untrusted domain"

**Comment by yatzy** [comment]
Thanks slomo-official for the suggestion! Unfortunately that did not help in my case.

**Comment by wabuMike** [comment]
@slomo-official Thanks for mentioning! @kyrofa I ran into the same issue! Would you mind updating the wiki article? If the data directory is in `/media/my/new/data`, root must also own the directory `/media/my/new`!

> I had the same issue when following the instructions from [https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition](url)
> Solved it by running `sudo chown -R root:root /mnt/nextcloud` meaning one folder above the data folder

**Comment by talski** [comment]
make sure the mount point is also owned by root (/media/mymountingpoint), mine was owned by my current user, changed to root and everything was working again

**Comment by Quazmoz** [comment]
> make sure the mount point is also owned by root (/media/mymountingpoint), mine was owned by my current user, changed to root and everything was working again

Thank you for this suggestion! It didn't work for me however it led me to change the owner to www-data and it is working now

**Comment by 71ae** [comment]
I have installed Ubuntu 20.04 with Snap.

When I follow the steps from this wiki article
https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

the file autoconfig.php is reverted back to its recent version after a couple of seconds, and the config doesn't come into effect.

**Comment by Poohblah** [comment]
I ran into this same error message, after following the aforementioned instructions in the wiki to the letter, also using the Nextcloud Snap on Ubuntu.

It turns out there was a symlink in my data directory path in config.php.  Apparently Nextcloud did not appreciate that.  I used the full path instead and that resolved the issue.

@71ae the instructions state to edit config.php, not autoconfig.php.

**Comment by Hunk3n** [comment]
Hello,

I am facing the same problem. I have installed nextcloud with the snap method. Everything is going well but I am out of space. So I have bought a new hard drive. The problem is that I do not manage to move the data directory to the new hard drive. Let me summarize what I have done:

- Plug the HDD
 - Create a location `/media/HDD_storage`
 - Change the `/etc/fstab ` file by adding a new line `UUID=... /media/HDD_storage ext4 defaults 0 2`
- Reboot my computer to automount the disk

 Then I have followed the guide from the github page Nextcloud-snap
` $ sudo snap connect nextcloud:removable-media`
` $ sudo mkdir -p /media/HDD_storage/nextcloud`
 `$ sudo chown -R root:root /media/HDD_storage/nextcloud`

   I stop the snap running

 `$ sudo snap stop nextcloud`

   I have change the path to the new directory in the config.php file

```
 // ...
 'datadirectory' => '/media/HDD_storage/nextcloud/data',
 // ...
```

For the first try I did

 `$ sudo cp -R /var/snap/nextcloud/common/nextcloud/data /media/HDD_storage/nextcloud/`

The first try was not working so I tried this after removing the previous folder

` $ sudo mv /var/snap/nextcloud/common/nextcloud/data /media/HDD_storage/nextcloud/`

Finally I restart the snap

`$ sudo snap start nextcloud`

Unfortunately, it does not work. I get the following error message from the browser:

```
Your data directory is invalid Ensure there is a file called ".ocdata" in the root of the data directory. Cannot create "data" directory This can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/22/go.php?to=admin-dir_permissions
```

 I move back the directory, still with mv, and I went back to the first config.php file

`'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data'`

and know it is working again but I am still out of space. I already check some stuff.
- The `.ocdata` file exists
- The owner of the data directory `drwxrwx--- 7 root          root          4096 nov    9  2021 data/`
-  The owner of the nextcloud directory `drwxrwxr-x 3 root          root           4096 nov.  9 2021 nextcloud/`

Could someone help me to understand what is wrong? 


Thanks for reading.

**Comment by volgunov-ad** [comment]
Пару дней назад периодически я начал получать сообщения об отсутствии файла .ocdata. Через несколько секунд, после обновления страницы работа сервера восстанавливается. Указанный файл присутствует, путь к datadir указан верно, права установлены на пользователя www-data. Мне кажется это началось после автоматическогг обновления
Nextcloudpi on odroid xu4 with armbian

![4CA44705-2864-4EAF-865B-9DBCD838CD57](https://user-images.githubusercontent.com/49494627/143493550-0da2eb0a-6b80-41c7-bf1c-c63da524ad03.jpeg)

**Comment by fazzer4x** [comment]
> **SOLVED** To solve this issue I have just changed the path from `/media/HDD_storage/nextcloud/data` to `/media/HDD_storage/data/` and now everything is working.

Help me understand your solution please. Did you only change the path in the config or did you change the location of the data to /media/HDD/data as well?

**Comment by Jachhj-sc** [comment]
> I had the same issue when following the instructions from [https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition](url) Solved it by running `sudo chown -R root:root /mnt/nextcloud` meaning one folder above the data folder

Thanks fixed it for me.

**Comment by Davros23** [comment]
> I had the same issue when following the instructions from [https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition](url) Solved it by running `sudo chown -R root:root /mnt/nextcloud` meaning one folder above the data folder

Permissions! It's always permissions...
