### ISSUE TITLE
After upgrading to 13.0.6snap1 custom theming doesn't work

### ISSUE THREAD

**Issue by imilos** [nextcloud-snap/nextcloud-snap#732]
After upgrading to 13.0.6snap1 chaniging theme to custom logo, colour and background does not work. Tried disabling/enabling snap, but theme remains default.

**Comment by imilos** [comment]
I also did `snap revoke nextcloud` to revert to 13.0.5snap1, but Theming still doesn't work (as it used to). No obvious traces in the log. Any workaround?

**Comment by imilos** [comment]
Snap heas been updated to 13.0.7snap1, but still no luck with theming.

**Comment by kyrofa** [comment]
@imilos this works fine for me in 13.0.7snap1, I've tested the color, logo, and login image, all seem to work. None of that stuff works for you?

**Comment by kyrofa** [comment]
Out of curiosity, does clearing the JS and CSS caches help at all?

Ah, I wonder if this is indeed because you do so much testing/reverting etc. Basically, Nextcloud puts the JS and CSS cache in the datadir, which as you know is in `$SNAP_COMMON`, and thus isn't included in a revert. Try clearing out those caches (this is assuming your data is still in the default place, if not, replace `/var/snap/nextcloud/common/nextcloud/data` with your datadir):

```
$ sudo rm -r /var/snap/nextcloud/common/nextcloud/data/appdata_*/css/* /var/snap/nextcloud/common/nextcloud/data/appdata_*/js/*
```
Then re-generate:
```
$ sudo nextcloud.occ files:scan-app-data
```

**Comment by imilos** [comment]
Thanks for your quick reply @kyrofa . I did that what you proposed, even disabled  and enabled snap, but still no luck. The only setting that remains is the colour setting. Name, link, slogan, logo... do not appear at all....

**Comment by joshuacox** [comment]
Which directory are the themes supposed to be placed in?

It seems there are a [few](https://github.com/nextcloud/nextcloud-snap/wiki/Finding-files) but I'm not certain which I'm supposed to be meddling in.

**Comment by imilos** [comment]
The issue remains even after snap has been updated to Nextcloud 14.05.

**Comment by Bleuzen** [comment]
Issue is still there. Any news on this?
