### ISSUE TITLE
/etc/ldap/ldap.conf is not read when installed via snap

### ISSUE THREAD

**Issue by thermionic** [nextcloud-snap/nextcloud-snap#775]
### Steps to reproduce
clean install of Ubuntu 18.0.4 server

1. sudo add-apt-repository universe
2. sudo apt-get update
3. sudo apt-get dist-upgrade
4. sudo apt-get install inotify-tools
5. sudo inotifywait -m /etc/ldap/ldap.conf
6. sudo snap install nextcloud
7. enable Nextcloud app "LDAP user and group backend"
8. add LDAP host, credentials and base DN
9. click Test Base DN

### Expected behaviour
ldap.conf should be read

### Actual behaviour
ldap.conf is not read

### Server configuration

**Ubuntu 18.04**:

**Web server: as installed by sudo snap install nextcloud**

**Database: as installed by sudo snap install nextcloud**

**PHP version: as installed by sudo snap install nextcloud**

**Nextcloud version:13.06  as installed by sudo snap install nextcloud**

**fresh install:**

**Where did you install Nextcloud from:**
 as installed by sudo snap install nextcloud

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
as installed by sudo snap install nextcloud
LDAP user and group backend

**Comment by thermionic** [comment]
Alternatively, if somebody can provide a way to use a private certificate with LDAPS...

**Comment by kyrofa** [comment]
The snap is confined, I don't think it's possible for it to snoop on the host's `/etc/ldap/ldap.conf`.

**Comment by kyrofa** [comment]
Regarding a private cert, can you give me more details as to what you're talking about? @adhami03 might have some ideas.

**Comment by thermionic** [comment]
The reason is quite simple, with LDAP auth the users credentials are sent in cleartext between nextcloud and the LDAP (in this case a Windows AD DC (Active Directory Domain Controller) server.

Sending credentials in cleartext is somethign to be avoided, hence LDAPS. 

from https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap.html#ssl-certificate-verification-ldaps-tls

> A common mistake with SSL certificates is that they may not be known to PHP

The most common LDAP server is an AD DC. Whiel it is "possible" to replace an internal PKI cert with a public cert (such as a letsencrypt cert), when there is an existing internal PKI deplyment (most AD environments), replacing the internal cert with a public cert can have a LOT of other work attached to it.

> If you have trouble with certificate validation make sure that
> - You have the certificate of the server installed on the Nextcloud server
> - The certificate is announced in the system’s LDAP configuration file (usually /etc/ldap/ldap.conf)
> - Using LDAPS, also make sure that the port is correctly configured (by default 636)

The inability to read the system ldap.conf (and root certificate listed in there) is not the problem, the problem is being unable to use LDAPS with a private cert.

**Comment by kyrofa** [comment]
> The inability to read the system ldap.conf (and root certificate listed in there) is not the problem

Wait... isn't that what this issue is about? Or would you like to rewrite it?

> [...] the problem is being unable to use LDAPS with a private cert.

Why are you unable to do this? What is standing in your way?

**Comment by kyrofa** [comment]
So I'm looking at the ldap app, and it looks like there's no place to say "hey, trust this private cert", it seems to assume that ldaps is protected by a public CA. Is that what you're talking about?

**Comment by thermionic** [comment]
My bad "the problem" should have been "the problem I am facing". 

Would you be happier if I rewrote the issue to be specifically about the inability to use a private cert ?

I'm a little lost as to why were unable to see a method to trust a private certificate, the nextcloud documentation that I linked to covers the method to use for a private CA, the method is to edit ldap.conf and provide a path to the certificate (or directory with many certificates)

For more detail see the TLS_CACERT/TLS_CACERTDIR options here https://www.openldap.org/software/man.cgi?query=ldap.conf

**Comment by kyrofa** [comment]
Ah ha, I see-- and since you can't access the system's ldap.conf, you can't do that. Taking a quick read of http://php.net/manual/en/function.ldap-connect.php#36156 makes me think you might be able to get away with putting these settings in `/root/snap/nextcloud/current/.ldaprc` (`$HOME` for apache). Can you give that a shot?

**Comment by thermionic** [comment]
Following the canonical documentation https://www.openldap.org/software/man.cgi?query=ldap.conf I tried with .ldaprc and ldaprc in /root/snap/nextcloud/current

Unfortunately with the simple test that I outlined in the first post in this issue, neither file is read on either the startup of the snap, or when an LDAP/LDAPS connection is made, and predictably LDAPS connections still fail.

**Comment by thermionic** [comment]
Any ideas ??

**Comment by izavneicigam** [comment]
As a workaround you can temporary disable the certificate check (useful in that circumstance when self-signed and even if system wide, but not recognized within snap environment), even if a shame to not be able to verify the remote ldap server (and avoid man in the middle...)

Hope a better solution will raise soon

nextcloud.occ ldap:set-config s01 turnOffCertCheck 1

**Comment by panholzerp** [comment]
+1 for LDAPS. As it is right now, the SNAP installation does not support LDAP integration in a productive environment, as it cannot be done securely. This should be reflected in the documentation, as it saves a lot of time to avoid the SNAP for environments where LDAP integration is required.

Disabling the certificate check is - from a security perspective - the same as using LDAP instead of LDAPS. Your LDAP user passwords will be readable by men-in-the-middle!

**Comment by izav** [comment]
Yes but you:
- will be able to use snap when necessary
- passwords will not be in clear text (next hops will see things encrypted)

As said, yes this is not perfect i.e against mitm even if be able to put a ldap server in between nextcloud and official ldap server is probably something you can avoid with otjer solutions line a vpn/tunnel.

**Comment by panholzerp** [comment]
Only if you mean legitimate, trusted next hop. A man in the middle anywhere in the same network will see the passwords in cleartext if ldaps is used with disabled certificate check.

**Comment by kyrofa** [comment]
> Disabling the certificate check is - from a security perspective - the same as using LDAP instead of LDAPS. Your LDAP user passwords will be readable by men-in-the-middle!

This is not true. It's like saying self-signed certs are the same as not using certs at all. Disabling the cert check doesn't disable encryption, it disables cert verification. This indeed makes it _easier_ to conduct a mitm attack, but it certainly doesn't imply this:

> A man in the middle anywhere in the same network will see the passwords in cleartext

**Comment by thermionic** [comment]
@kyrofa I fail to see why you are arguing the point.

With certificate verification disabled, **anything** on the same network can intercept the traffic and recover the plaintext **without detection**.

**Comment by kyrofa** [comment]
Because there's a large difference between "it's possible to mitm" and "it's sending passwords in plaintext" and I want to make sure folks know that. I'm not debating that disabling the check is a solution-- it's not. However, it seems that no real solution is forthcoming without our needing to modify PHP ldap lib. If someone wants to work on that, feel free.

**Comment by panholzerp** [comment]
> Because there's a large difference between "it's possible to mitm" and "it's sending passwords in cleartext" and I want to make sure folks know that.

I try to give it a last shot: in my opinion as a security professional the difference between plain ldap and ldaps without certificate check is negligible. Yes, the traffic is encrypted, but with a key that is known by the attacker if the attacker is a man-in-the-middle. The same goes for HTTPS with a certificate warning in your browser: it is hardly better than plain HTTP. Why? Because the attacker just starts up a simple tool (e.g. bettercap) and can read the clear text. The only argument that I see is that a missing certificate check requires an active attack by the man-in-the-middle while contents of unencrypted traffic could be accidentally leaked in e.g. log files.

> However, it seems that no real solution is forthcoming without our needing to modify PHP's ldap lib. If someone wants to work on that, feel free, but do not use my issues to spread FUD.

OK, let's discuss solutions. PHP's ldap lib is not the problem, as it is fully capable of doing the right checks. But to do so, it must have access to the configured CA certificate that was used to sign the LDAPS server certificate. So this is a SNAP installation only issue, there is no problem with a manual installation of Nextcloud. To me it seems that we need to do two things:

1. Make the certificate accessible from within the SNAP
2. Point the ldap client to the certificate

1. could be resolved by mounting the /etc/ssl/certs directory of the host system read only into the snap
2. could be resolved by mounting the /etc/ldap directory of the host system read only into the snap OR set the LDAPTLS_CACERT environment variable within the snap

Has anyone a good suggestion to do this in en elegant way that will survive the next snap update?

give

**Comment by kyrofa** [comment]
> OK, let's discuss solutions. PHP's ldap lib is not the problem, as it is fully capable of doing the right checks. But to do so, it must have access to the configured CA certificate that was used to sign the LDAPS server certificate. So this is a SNAP installation only issue, there is no problem with a manual installation of Nextcloud. To me it seems that we need to do two things:
>
> 1. Make the certificate accessible from within the SNAP
    This could be resolved by mounting the /etc/ssl/certs directory of the host system read only into the snap.

This isn't possible, it's not how snaps work. They're meant to be isolated. There are some certs in `/etc/ssl/certs`, but they come in the core snap and aren't modifiable.

> 2. Point the ldap client to the certificate
    This could be resolved by mounting the /etc/ldap directory of the host system read only into the snap OR set the LDAPTLS_CACERT environment variable within the snap.

As above, and as I've said multiple times, snaps _cannot_ see the host `/etc/ldap`. This isn't a feature missing from this snap, it's something that snaps by design simply cannot do. The modification to PHP LDAP that I was mulling over was some way to point it to an alternative config or alternative CA, but then you mention this environment variable, which is new to me. I can't seem to find docs on that, do you know where any might be?

**Comment by bognerf** [comment]
You could use the env variable like this:

```php
putenv('LDAPTLS_CACERT=' . $absolutePathToPEMfile);
```
It could, of course, be set outside of an PHP script as well via `export`.

I don't have any links to a documentation, but I can assure you it works. I'm using this possibility myself to make dockerized unit tests of an LDAP abstraction library work.

**Comment by panholzerp** [comment]
> This isn't possible, it's not how snaps work. They're meant to be isolated. There are some certs in /etc/ssl/certs, but they come in the core snap and aren't modifiable.

That is not entirely true. With the command `sudo mount --bind -o nodev,ro /etc/ssl/certs /snap/core/current/etc/ssl/certs/` you can mount the certs of the host directory into the snap. I have verified this by 

1. snap run --shell nextcloud.apache
2. cat /etc/ssl/certs/my.cer

> I can't seem to find docs on that, do you know where any might be?
man ldap.conf

All I am asking the community for is to help me bring all these pieces together to a nice, maintainable solution (i.e. that keeps working after a snap refresh). Right now I would assume the solution is to run a startup script that does the mount and sets the env variable. But I do not know yet how to do the second step.

**Comment by kyrofa** [comment]
Thanks @bognerf, that may be the solution right there. @panholzerp, binding-mounting stuff on top of the snap is a hack, will likely not work consistently, and is not supported. We need a solution that works out of the box when the snap is installed.
