### ISSUE TITLE
Improvements for export

### ISSUE THREAD

**Issue by Bleuzen** [nextcloud-snap/nextcloud-snap#955]
Hi, I like to use the nextcloud.export command for backups. There are two things which could be improved:
 - Make it possible to select the output directory. In my case I have it installed on a raspberry pi and want to backup to an external usb device, no need to put the backup on the sd card.
 - Add option to backup to one file (.tar) (maybe also an option for .tar.gz, in case some users like compression)

**Comment by kyrofa** [comment]
> Make it possible to select the output directory. In my case I have it installed on a raspberry pi and want to backup to an external usb device, no need to put the backup on the sd card.

I agree this would be nice, but I'm afraid it's not possible while still being confined. The fact is, the snap can only write to certain areas on your disk. If you were able to request that it write elsewhere, it would simply barf out "permission denied" most of the time unless you happened to select an area accessible while under confinement. That's why we elected to just write it to a predictable place and you could move it out on your own if you so desired.

- Add option to backup to one file (.tar) (maybe also an option for .tar.gz, in case some users like compression)

I wanted this as well, but so far it's not proven feasible. The issue is that, in order to create a .tar, one must create a directory to be tarred (i.e. you can't stream multiple files into a .tar). That means you need, at least temporarily, double the space in order to create a .tar (1 for a directory, and then 1 for the .tar of the directory, before you can blow away the directory and keep the .tar). Given that these backups include the raw data, that seemed to be a poor assumption to make (i.e. it would certainly not work for me). If you know of a compression method that doesn't have this issue, please let me know.

An additional benefit of the current method is that you can use hard links between backups for files that haven't changed. If you compressed it that would be impossible.

**Comment by Bleuzen** [comment]
> I agree this would be nice, but I'm afraid it's not possible while still being confined. The fact is, the snap can only write to certain areas on your disk. If you were able to request that it write elsewhere, it would simply barf out "permission denied" most of the time unless you happened to select an area accessible while under confinement. That's why we elected to just write it to a predictable place and you could move it out on your own if you so desired.

Well it's possible to move the nextcloud data directory to a removable disk, so I thought it would also be possible to save the backups on a external disk using the same way.
Even if it would be only selectable under /media it would be ok.



> I wanted this as well, but so far it's not proven feasible. The issue is that, in order to create a .tar, one must create a directory to be tarred (i.e. you can't stream multiple files into a .tar). That means you need, at least temporarily, double the space in order to create a .tar (1 for a directory, and then 1 for the .tar of the directory, before you can blow away the directory and keep the .tar). Given that these backups include the raw data, that seemed to be a poor assumption to make (e.g. it would certainly not work for me). If you know of a compression method that doesn't have this issue, please let me know.

Here is an example of how NextcloudPi is doing it:
https://github.com/nextcloud/nextcloudpi/blob/master/bin/ncp/BACKUPS/nc-backup.sh

Is it really required to copy the files to another location first? Why not take the data directory which is already there as input directory for tar?

**Comment by kyrofa** [comment]
> Well it's possible to move the nextcloud data directory to a removable disk, so I thought it would also be possible to save the backups on a external disk using the same way.

That assumes that the `removable-media` interface is connected, which it isn't by default. While I understand that how this works today isn't ideal, I think it's the best we can do for now without introducing the possibility of more bugs being logged ("why can't I ask the tool to backup \<here\>?").

> Is it really required to copy the files to another location first? Why not take the data directory which is already there as input directory for tar?

It's been a while since I investigated this, but I tried to outline the issues I ran into [here](https://github.com/nextcloud/nextcloud-snap/pull/688#issuecomment-421405839). If you know of a way around those issues, please feel free to take a crack at this!

**Comment by michaelblyons** [comment]
I'm trying to import a NextCloudPi backup. I managed to move around bits and pieces of the NCP export such that `nexcloud.import` is "successful" (thanks for the link to #688!), but NextCloud itself is _super_ mad now:

```
$ sudo nextcloud.occ
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /snap/nextcloud/15910/htdocs/lib/private/DB/Connection.php:64
Stack trace:
#0 /snap/nextcloud/15910/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /snap/nextcloud/15910/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /snap/nextcloud/15910/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /snap/nextcloud/15910/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /snap/nextcloud/15910/htdocs/lib/private/DB/Connection.php(151): Doctrine\DBAL\
```

Do I basically need to reinstall the snap and dump data in from the frontend?
